# Generated by Django 5.0.1 on 2025-05-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', 'create_med_access_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='medical_record_access_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='medical_record_otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='medical_record_otp_created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='medical_record_token_created_at',
        ),
    ]
