# Generated by Django 5.1.3 on 2025-02-25 00:47

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "department_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical Department"),
                            ("surgical", "Surgical Department"),
                            ("emergency", "Emergency Department"),
                            ("critical_care", "Critical Care"),
                            ("outpatient", "Outpatient Clinic"),
                            ("laboratory", "Laboratory"),
                            ("radiology", "Radiology"),
                            ("pharmacy", "Pharmacy"),
                            ("physiotherapy", "Physiotherapy"),
                            ("admin", "Administration"),
                            ("records", "Medical Records"),
                            ("it", "Information Technology"),
                        ],
                        help_text="Type/Category of the department",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "floor_number",
                    models.CharField(
                        help_text="Floor number where the department is located",
                        max_length=10,
                    ),
                ),
                (
                    "wing",
                    models.CharField(
                        choices=[
                            ("north", "North Wing"),
                            ("south", "South Wing"),
                            ("east", "East Wing"),
                            ("west", "West Wing"),
                            ("central", "Central Wing"),
                        ],
                        help_text="Hospital wing where the department is located",
                        max_length=50,
                    ),
                ),
                (
                    "extension_number",
                    models.CharField(
                        help_text="Internal telephone extension", max_length=10
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        help_text="Emergency contact number", max_length=20
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Department email address", max_length=254
                    ),
                ),
                (
                    "is_24_hours",
                    models.BooleanField(
                        default=False, help_text="Whether the department operates 24/7"
                    ),
                ),
                (
                    "operating_hours",
                    models.JSONField(
                        default=dict,
                        help_text="Operating hours for each day of the week",
                    ),
                ),
                (
                    "total_beds",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of regular beds"
                    ),
                ),
                (
                    "occupied_beds",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of occupied regular beds"
                    ),
                ),
                (
                    "icu_beds",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of ICU beds"
                    ),
                ),
                (
                    "occupied_icu_beds",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of occupied ICU beds"
                    ),
                ),
                (
                    "bed_capacity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total bed capacity including regular and ICU beds",
                    ),
                ),
                (
                    "current_patient_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current number of patients in the department",
                    ),
                ),
                (
                    "minimum_staff_required",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum number of staff required for safe operation",
                    ),
                ),
                (
                    "current_staff_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current number of active staff in the department",
                    ),
                ),
                (
                    "recommended_staff_ratio",
                    models.FloatField(
                        default=1.0, help_text="Recommended staff to patient ratio"
                    ),
                ),
                (
                    "annual_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual budget allocation for the department",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "budget_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Fiscal year for the budget", null=True
                    ),
                ),
                (
                    "budget_utilized",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount of budget utilized so far",
                        max_digits=12,
                    ),
                ),
                (
                    "equipment_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget allocated for equipment and maintenance",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "staff_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget allocated for staff salaries and benefits",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "appointment_duration",
                    models.PositiveIntegerField(
                        default=30, help_text="Default appointment duration in minutes"
                    ),
                ),
                (
                    "max_daily_appointments",
                    models.PositiveIntegerField(
                        default=50, help_text="Maximum number of appointments per day"
                    ),
                ),
                (
                    "requires_referral",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this department requires referral for appointments",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GPPractice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("patient", "Patient"),
                            ("doctor", "Doctor"),
                            ("nurse", "Nurse"),
                            ("pharmacist", "Pharmacist"),
                            ("lab_technician", "Laboratory Technician"),
                            ("receptionist", "Receptionist"),
                            ("admin", "Admin"),
                            ("physician_assistant", "Physician Assistant"),
                            ("medical_secretary", "Medical Secretary"),
                            ("physical_therapist", "Physical Therapist"),
                            ("occupational_therapist", "Occupational Therapist"),
                            ("social_worker", "Social Worker"),
                            ("psychologist", "Psychologist"),
                            ("counselor", "Counselor"),
                            ("radiologist_tech", "Radiology Technician"),
                            ("dietitian", "Dietitian/Nutritionist"),
                            ("case_manager", "Case Manager"),
                            ("home_health_aide", "Home Health Aide"),
                            ("medical_records_clerk", "Medical Records Clerk"),
                            ("it_support", "IT Support Specialist"),
                            ("data_analyst", "Health Data Analyst"),
                            ("hospital_admin", "Hospital Administrator"),
                            ("insurance_coordinator", "Insurance Coordinator"),
                            ("billing_specialist", "Billing Specialist"),
                            ("patient_advocate", "Patient Advocate"),
                            ("compliance_officer", "Compliance Officer"),
                            ("clinical_researcher", "Clinical Researcher"),
                            ("biomedical_engineer", "Biomedical Engineer"),
                            ("paramedic", "Paramedic"),
                            ("emt", "Emergency Medical Technician (EMT)"),
                            ("midwife", "Midwife"),
                            ("dentist", "Dentist"),
                            ("dental_hygienist", "Dental Hygienist"),
                            ("medical_interpreter", "Medical Interpreter"),
                            ("speech_therapist", "Speech-Language Pathologist"),
                            ("pharmacy_tech", "Pharmacy Technician"),
                            ("infection_control", "Infection Control Specialist"),
                            ("qa_officer", "Quality Assurance Officer"),
                            ("volunteer_coordinator", "Volunteer Coordinator"),
                            ("hr_manager", "Human Resources Manager"),
                        ],
                        default="patient",
                        max_length=30,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "nin",
                    models.CharField(blank=True, max_length=11, null=True, unique=True),
                ),
                ("consent_terms", models.BooleanField(default=False)),
                ("consent_hipaa", models.BooleanField(default=False)),
                ("consent_data_processing", models.BooleanField(default=False)),
                (
                    "hpn",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=30,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_token",
                    models.UUIDField(default=uuid.uuid4, unique=True),
                ),
                (
                    "password_reset_token",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "social_provider",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("social_id", models.CharField(blank=True, max_length=255, null=True)),
                ("has_completed_onboarding", models.BooleanField(default=False)),
                ("is_email_verified", models.BooleanField(default=False)),
                (
                    "email_verification_token",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("otp_created_at", models.DateTimeField(blank=True, null=True)),
                ("otp_required_for_login", models.BooleanField(default=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DepartmentEmergency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("required_staff", models.PositiveIntegerField()),
                ("declared_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneralPractitioner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("specializations", models.TextField(blank=True)),
                (
                    "clinic_location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location of the clinic",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Consultation fee in local currency",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "available_days",
                    models.CharField(
                        default="Monday to Friday",
                        help_text="e.g., Monday to Friday",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gp_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="general_practitioners",
                        to="api.gppractice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="current_gp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_patients",
                to="api.generalpractitioner",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gp_practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="api.gppractice",
            ),
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Hospital's latitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Hospital's longitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Hospital registration number",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateField(blank=True, null=True)),
                (
                    "hospital_type",
                    models.CharField(
                        choices=[
                            ("public", "Public Hospital"),
                            ("private", "Private Hospital"),
                            ("specialist", "Specialist Hospital"),
                            ("teaching", "Teaching Hospital"),
                            ("clinic", "Clinic"),
                            ("research", "Research Institution"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("bed_capacity", models.PositiveIntegerField(default=0)),
                ("emergency_unit", models.BooleanField(default=True)),
                ("icu_unit", models.BooleanField(default=False)),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Hospital contact email",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("accreditation_status", models.BooleanField(default=False)),
                ("accreditation_expiry", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospitals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gppractice",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gp_practices",
                to="api.hospital",
            ),
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        help_text="Doctor's medical specialization", max_length=100
                    ),
                ),
                (
                    "medical_license_number",
                    models.CharField(
                        help_text="Medical license registration number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "license_expiry_date",
                    models.DateField(help_text="Medical license expiry date"),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        help_text="Years of professional experience"
                    ),
                ),
                (
                    "qualifications",
                    models.JSONField(
                        default=list,
                        help_text="List of academic and professional qualifications",
                    ),
                ),
                (
                    "board_certifications",
                    models.TextField(
                        blank=True, help_text="Medical board certifications", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the doctor is currently practicing",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On Leave"),
                            ("suspended", "Suspended"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        help_text="Current working status",
                        max_length=20,
                    ),
                ),
                (
                    "available_for_appointments",
                    models.BooleanField(
                        default=True, help_text="Whether accepting new appointments"
                    ),
                ),
                (
                    "consultation_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start time of consultation hours",
                        null=True,
                    ),
                ),
                (
                    "consultation_hours_end",
                    models.TimeField(
                        blank=True,
                        help_text="End time of consultation hours",
                        null=True,
                    ),
                ),
                (
                    "consultation_days",
                    models.CharField(
                        help_text="Comma-separated days, e.g., 'Mon,Tue,Wed'",
                        max_length=100,
                    ),
                ),
                (
                    "max_daily_appointments",
                    models.PositiveIntegerField(
                        default=20, help_text="Maximum appointments per day"
                    ),
                ),
                (
                    "appointment_duration",
                    models.PositiveIntegerField(
                        default=30, help_text="Default appointment duration in minutes"
                    ),
                ),
                (
                    "surgical_subspecialty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minimally_invasive", "Minimally Invasive Surgery"),
                            ("robotic_surgery", "Robotic Surgery"),
                            ("transplant_surgery", "Transplant Surgery"),
                            ("bariatric_surgery", "Bariatric Surgery"),
                            ("oncologic_surgery", "Oncologic Surgery"),
                            ("pediatric_surgery", "Pediatric Surgery"),
                            ("cosmetic_surgery", "Cosmetic Surgery"),
                        ],
                        help_text="Required only for surgical departments",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "research_interests",
                    models.TextField(
                        blank=True, help_text="Areas of research interest", null=True
                    ),
                ),
                (
                    "publications",
                    models.TextField(
                        blank=True, help_text="Published research works", null=True
                    ),
                ),
                (
                    "languages_spoken",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated languages",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "medical_school",
                    models.CharField(
                        blank=True,
                        help_text="Medical school attended",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "graduation_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Year of graduation from medical school",
                        null=True,
                    ),
                ),
                (
                    "office_phone",
                    models.CharField(
                        blank=True,
                        help_text="Office contact number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "office_location",
                    models.CharField(
                        blank=True,
                        help_text="Office location within hospital",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether credentials are verified"
                    ),
                ),
                (
                    "verification_documents",
                    models.FileField(
                        blank=True,
                        help_text="Credential verification documents",
                        null=True,
                        upload_to="doctor_verifications/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department where the doctor primarily works",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctors",
                        to="api.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account associated with this doctor",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        help_text="Primary hospital affiliation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctors",
                        to="api.hospital",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_prescribe", "Can prescribe medications"),
                    ("can_view_patient_records", "Can view patient records"),
                    ("can_update_patient_records", "Can update patient records"),
                    ("can_perform_surgery", "Can perform surgical procedures"),
                    ("can_admit_patients", "Can admit patients to hospital"),
                    ("can_discharge_patients", "Can discharge patients"),
                    ("can_order_tests", "Can order medical tests"),
                    ("can_view_test_results", "Can view test results"),
                ],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="api.hospital",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="api.hospital",
            ),
        ),
        migrations.CreateModel(
            name="HospitalAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.hospital"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.hospital"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hpn", models.CharField(max_length=30, unique=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("allergies", models.TextField(blank=True, null=True)),
                ("chronic_conditions", models.TextField(blank=True, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_high_risk", models.BooleanField(default=False)),
                ("last_visit_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("transfer_date", models.DateField()),
                ("effective_date", models.DateField()),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Transfer Completed"),
                            ("cancelled", "Transfer Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Detailed reason for the transfer request"
                    ),
                ),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional information about the transfer",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason if transfer is rejected",
                        null=True,
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent Transfer"),
                            ("temporary", "Temporary Transfer"),
                            ("rotation", "Rotation Program"),
                            ("emergency", "Emergency Transfer"),
                        ],
                        default="permanent",
                        max_length=20,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="End date for temporary transfers",
                        null=True,
                    ),
                ),
                (
                    "approved_by_destination",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_incoming_transfers",
                        to="api.hospitaladmin",
                    ),
                ),
                (
                    "approved_by_source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_outgoing_transfers",
                        to="api.hospitaladmin",
                    ),
                ),
                (
                    "from_department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="api.department",
                    ),
                ),
                (
                    "from_hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="api.hospital",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_transfers",
                        to="api.hospitaladmin",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="api.department",
                    ),
                ),
                (
                    "to_hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="api.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["-request_date"],
            },
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(
                fields=["registration_number"], name="api_hospita_registr_d9877c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(
                fields=["hospital_type"], name="api_hospita_hospita_892dc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(
                fields=["is_verified"], name="api_hospita_is_veri_7b6d68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["medical_license_number"], name="api_doctor_medical_b30a26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["department"], name="api_doctor_departm_0ab481_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(fields=["status"], name="api_doctor_status_a88f78_idx"),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["hospital"], name="api_doctor_hospita_b395bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["specialization"], name="api_doctor_special_a2cf69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["is_active", "available_for_appointments"],
                name="api_doctor_is_acti_2255ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="dept_code_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["department_type"], name="dept_type_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["is_active"], name="dept_active_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["is_24_hours"], name="dept_24hr_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["wing"], name="dept_wing_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["hospital", "department_type"], name="dept_hosp_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["hospital", "is_active"], name="dept_hosp_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["current_patient_count"], name="dept_patient_count_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["current_staff_count"], name="dept_staff_count_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("hospital", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="hospitalregistration",
            unique_together={("user", "hospital")},
        ),
        migrations.AddIndex(
            model_name="stafftransfer",
            index=models.Index(fields=["status"], name="api_stafftr_status_159b87_idx"),
        ),
        migrations.AddIndex(
            model_name="stafftransfer",
            index=models.Index(
                fields=["transfer_date"], name="api_stafftr_transfe_b62c77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stafftransfer",
            index=models.Index(
                fields=["staff_member"], name="api_stafftr_staff_m_e68b30_idx"
            ),
        ),
    ]
