# Generated by Django 5.0.1 on 2025-05-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_medical_record_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('african', 'African'), ('arab', 'Arab'), ('asian', 'Asian'), ('caribbean', 'Caribbean'), ('caucasian', 'Caucasian/White'), ('hispanic', 'Hispanic/Latino'), ('mediterranean', 'Mediterranean'), ('middle_eastern', 'Middle Eastern'), ('mixed', 'Mixed/Multiple ethnic groups'), ('pacific_islander', 'Pacific Islander'), ('south_asian', 'South Asian'), ('southeast_asian', 'Southeast Asian'), ('indigenous', 'Indigenous/Aboriginal'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text="Patient's ethnic background (used for health risk assessments)", max_length=20, null=True),
        ),
    ]
