# Generated by Django 5.1.3 on 2025-02-25 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointmentfee_appointment_appointmentnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalregistration',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
