# Generated by Django 5.1.3 on 2025-02-20 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department_departmentemergency_doctor_hospitaladmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
