# Generated by Django 5.0.1 on 2025-05-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_medical_record_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medical_summary',
            field=models.TextField(blank=True, help_text='Summary of the appointment after completion', null=True),
        ),
    ]
