# Generated by Django 5.0.1 on 2025-05-06 19:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_ethnicity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryTestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the laboratory test', max_length=255)),
                ('code', models.CharField(help_text="Unique code for the test (e.g., 'CBC', 'LIPID', etc.)", max_length=50, unique=True)),
                ('category', models.CharField(help_text="Category of the test (e.g., 'Blood', 'Urine', 'Genetic')", max_length=100)),
                ('description', models.TextField(help_text='Detailed description of what the test measures')),
                ('sample_type', models.CharField(help_text="Type of sample required (e.g., 'Blood', 'Urine', 'Tissue')", max_length=100)),
                ('processing_time', models.CharField(help_text='Typical time to process this test', max_length=100)),
                ('fasting_required', models.BooleanField(default=False, help_text='Whether patient needs to fast before test')),
                ('reference_ranges', models.JSONField(default=dict, help_text='Reference ranges by age, gender, etc. (JSON format)')),
                ('units', models.CharField(help_text='Units of measurement for test results', max_length=50)),
                ('clinical_uses', models.TextField(help_text='Common clinical scenarios where this test is ordered')),
                ('result_interpretation', models.TextField(help_text='Guidelines for interpreting results')),
                ('associated_conditions', models.TextField(blank=True, help_text='Medical conditions commonly associated with abnormal results', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this test is currently available')),
                ('requires_approval', models.BooleanField(default=False, help_text='Whether test requires special approval')),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['code'], name='api_laborat_code_7b0666_idx'), models.Index(fields=['category'], name='api_laborat_categor_47fb17_idx'), models.Index(fields=['is_active'], name='api_laborat_is_acti_541319_idx')],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_date', models.DateTimeField(help_text='Date and time the test was performed')),
                ('result_date', models.DateTimeField(help_text='Date and time results were available')),
                ('result_value', models.CharField(help_text='Result value (may be numeric or descriptive)', max_length=255)),
                ('numeric_value', models.FloatField(blank=True, help_text='Numeric result value for trending (if applicable)', null=True)),
                ('units', models.CharField(help_text='Units of measurement', max_length=50)),
                ('reference_range_min', models.FloatField(blank=True, help_text='Lower limit of reference range', null=True)),
                ('reference_range_max', models.FloatField(blank=True, help_text='Upper limit of reference range', null=True)),
                ('reference_range_text', models.CharField(blank=True, help_text='Text description of reference range (for non-numeric results)', max_length=255, null=True)),
                ('is_abnormal', models.BooleanField(default=False, help_text='Whether result is outside normal range')),
                ('abnormal_flags', models.CharField(blank=True, help_text='Flags for abnormal results (H=High, L=Low, C=Critical, etc.)', max_length=20, null=True)),
                ('specimen_id', models.CharField(blank=True, help_text='ID of the specimen collected', max_length=100, null=True)),
                ('lab_facility', models.CharField(help_text='Name of lab facility that processed test', max_length=255)),
                ('processed_by', models.CharField(blank=True, help_text='Name of lab technician who processed the test', max_length=255, null=True)),
                ('clinical_notes', models.TextField(blank=True, help_text='Additional clinical notes about the test', null=True)),
                ('follow_up_recommended', models.BooleanField(default=False, help_text='Whether follow-up is recommended')),
                ('follow_up_notes', models.TextField(blank=True, help_text='Notes about recommended follow-up', null=True)),
                ('medical_record', models.ForeignKey(help_text='Medical record this result belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_results', to='api.medicalrecord')),
                ('ordered_by', models.ForeignKey(help_text='Doctor who ordered the test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_lab_tests', to='api.doctor')),
                ('test_type', models.ForeignKey(help_text='Type of laboratory test', on_delete=django.db.models.deletion.PROTECT, related_name='results', to='api.laboratorytesttype')),
            ],
            options={
                'ordering': ['-test_date'],
                'indexes': [models.Index(fields=['medical_record', 'test_date'], name='api_laborat_medical_fb036f_idx'), models.Index(fields=['test_type'], name='api_laborat_test_ty_b7539c_idx'), models.Index(fields=['is_abnormal'], name='api_laborat_is_abno_c96052_idx')],
            },
        ),
    ]
