# Generated by Django 5.1.3 on 2025-02-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hospitalregistration_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ar', 'Arabic'), ('sw', 'Swahili'), ('ha', 'Hausa'), ('yo', 'Yoruba'), ('ig', 'Igbo'), ('am', 'Amharic'), ('zu', 'Zulu'), ('xh', 'Xhosa'), ('pt', 'Portuguese')], default='en', help_text='Primary language for communication', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='secondary_languages',
            field=models.CharField(blank=True, help_text="Comma-separated list of language codes (e.g., 'fr,sw,ar')", max_length=50, null=True),
        ),
    ]
