# Generated by Django 5.1.3 on 2025-02-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_customuser_otp_customuser_otp_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="otp_required_for_login",
            field=models.BooleanField(default=True),
        ),
    ]
