# Generated by Django 5.1.3 on 2025-02-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_preferred_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_language',
            field=models.CharField(blank=True, help_text="If 'Other' is selected, please specify your preferred language", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ar', 'Arabic'), ('sw', 'Swahili'), ('ha', 'Hausa'), ('yo', 'Yoruba'), ('ig', 'Igbo'), ('am', 'Amharic'), ('zu', 'Zulu'), ('xh', 'Xhosa'), ('pt', 'Portuguese'), ('other', 'Other (Please specify)')], default='en', help_text='Primary language for communication', max_length=10),
        ),
    ]
