# Generated by Django 5.1.3 on 2025-02-20 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hospitalregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitaladmin',
            options={},
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='can_manage_departments',
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='can_manage_facilities',
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='can_manage_staff',
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='can_view_records',
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='last_login',
        ),
        migrations.AddField(
            model_name='hospitaladmin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospitaladmin',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
        ),
        migrations.AlterField(
            model_name='hospitaladmin',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='hospitaladmin',
            name='position',
            field=models.CharField(max_length=255),
        ),
    ]
