# Generated by Django 5.0.1 on 2025-05-06 19:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_laboratorytesttype_laboratoryresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_at', models.DateTimeField(help_text='Date and time when vitals were recorded')),
                ('location', models.CharField(blank=True, help_text="Location where vitals were recorded (e.g., 'ER', 'Home', 'Ward 4')", max_length=255, null=True)),
                ('context', models.CharField(blank=True, help_text="Context of measurement (e.g., 'Routine checkup', 'Post-surgery')", max_length=255, null=True)),
                ('systolic_bp', models.IntegerField(blank=True, help_text='Systolic blood pressure in mmHg', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)])),
                ('diastolic_bp', models.IntegerField(blank=True, help_text='Diastolic blood pressure in mmHg', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)])),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart rate in beats per minute', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)])),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Respiratory rate in breaths per minute', null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(60)])),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=2, help_text='Blood oxygen saturation in percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Body temperature', max_digits=5, null=True)),
                ('temperature_unit', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], default='C', help_text='Temperature unit', max_length=1)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Patient weight', max_digits=6, null=True)),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', help_text='Weight unit', max_length=2)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Patient height', max_digits=5, null=True)),
                ('height_unit', models.CharField(choices=[('cm', 'Centimeters'), ('in', 'Inches')], default='cm', help_text='Height unit', max_length=2)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, help_text='Body Mass Index (calculated field)', max_digits=5, null=True)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=2, help_text='Blood glucose level', max_digits=6, null=True)),
                ('glucose_unit', models.CharField(choices=[('mg/dL', 'mg/dL'), ('mmol/L', 'mmol/L')], default='mg/dL', help_text='Blood glucose unit of measurement', max_length=10)),
                ('glucose_timing', models.CharField(blank=True, choices=[('fasting', 'Fasting'), ('random', 'Random'), ('post_meal', 'Post-meal'), ('pre_meal', 'Pre-meal'), ('bedtime', 'Bedtime')], help_text='When glucose was measured relative to meals', max_length=20, null=True)),
                ('pain_scale', models.IntegerField(blank=True, help_text='Pain scale from 0-10', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('is_abnormal', models.BooleanField(default=False, help_text='Whether any vitals are outside normal range')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about these vital signs', null=True)),
                ('medical_record', models.ForeignKey(help_text='Medical record this vital sign belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='api.medicalrecord')),
                ('recorded_by', models.ForeignKey(help_text='Healthcare provider who recorded these vitals', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vital_signs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['medical_record', 'recorded_at'], name='api_vitalsi_medical_7d2cc3_idx'), models.Index(fields=['is_abnormal'], name='api_vitalsi_is_abno_92244a_idx')],
            },
        ),
    ]
