# Generated by Django 5.1.3 on 2025-02-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_customuser_otp_required_for_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("doctor", "Doctor"),
                    ("admin", "Admin"),
                ],
                default="patient",
                max_length=20,
            ),
        ),
    ]
