# Generated by Django 5.1.3 on 2025-02-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="has_completed_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
