# Generated by Django 5.1.3 on 2025-02-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_hospitaladmin_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalregistration',
            old_name='registration_date',
            new_name='created_at',
        ),
    ]
