# Generated by Django 5.1.3 on 2025-02-25 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_custom_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='chronic_care_experience',
            field=models.BooleanField(default=False, help_text='Whether doctor has experience with chronic conditions'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='complex_case_rating',
            field=models.FloatField(default=0.0, help_text='Rating for handling complex cases (0-10)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='continuity_of_care_rating',
            field=models.FloatField(default=0.0, help_text='Rating for maintaining continuity of care (0-10)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='expertise_codes',
            field=models.JSONField(default=list, help_text='List of ICD-10 codes the doctor specializes in'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='primary_expertise_codes',
            field=models.JSONField(default=list, help_text='List of primary ICD-10 codes (highest expertise)'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='care_plan_complexity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='comorbidity_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='hospitalization_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='last_hospitalization_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='medication_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DoctorInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_date', models.DateTimeField()),
                ('interaction_type', models.CharField(choices=[('appointment', 'Appointment'), ('consultation', 'Consultation'), ('procedure', 'Procedure'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=20)),
                ('patient_rating', models.IntegerField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('communication_issues', models.BooleanField(default=False)),
                ('communication_notes', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_interactions', to='api.doctor')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_interactions', to='api.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_code', models.CharField(max_length=10)),
                ('diagnosis_name', models.CharField(max_length=255)),
                ('diagnosis_date', models.DateTimeField()),
                ('is_chronic', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('severity_rating', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('diagnosed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_made', to='api.doctor')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='api.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('medication', 'Medication'), ('procedure', 'Procedure'), ('therapy', 'Therapy'), ('surgery', 'Surgery'), ('other', 'Other')], max_length=20)),
                ('treatment_name', models.CharField(max_length=255)),
                ('treatment_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='api.medicalrecord')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_prescribed', to='api.doctor')),
            ],
        ),
    ]
