# Generated by Django 5.1.3 on 2025-02-20 15:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_registration_date_hospitalregistration_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalregistration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hospitalregistration',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
