# Generated by Django 5.0.1 on 2025-05-06 19:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_familymedicalhistory_geneticinformation_immunization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generic_name', models.CharField(help_text='Generic name of the medication', max_length=255)),
                ('brand_names', models.JSONField(default=list, help_text='List of brand names for this medication')),
                ('drug_code', models.CharField(blank=True, help_text='Standard drug code (e.g., NDC or RxNorm)', max_length=50, null=True)),
                ('drug_class', models.CharField(help_text='Therapeutic class of medication', max_length=100)),
                ('atc_code', models.CharField(blank=True, help_text='WHO Anatomical Therapeutic Chemical code', max_length=10, null=True)),
                ('available_forms', models.JSONField(default=list, help_text='List of available forms (tablet, capsule, etc.)')),
                ('available_strengths', models.JSONField(default=list, help_text='List of available strengths with units')),
                ('standard_routes', models.JSONField(default=list, help_text='List of standard routes of administration')),
                ('indications', models.TextField(help_text='Common uses and indications')),
                ('contraindications', models.TextField(help_text='Conditions when medication should not be used')),
                ('side_effects', models.TextField(help_text='Common side effects')),
                ('serious_side_effects', models.TextField(help_text='Serious or life-threatening side effects')),
                ('warnings', models.TextField(help_text='Special warnings and precautions')),
                ('drug_interactions', models.JSONField(default=list, help_text='List of interacting drugs and effects')),
                ('food_interactions', models.TextField(blank=True, help_text='Food-drug interactions', null=True)),
                ('dosing_information', models.JSONField(default=dict, help_text='Structured dosing guidelines by condition, age, etc.')),
                ('max_daily_dose', models.CharField(blank=True, help_text='Maximum daily dose', max_length=100, null=True)),
                ('mechanism_of_action', models.TextField(blank=True, help_text='How the medication works in the body', null=True)),
                ('half_life', models.CharField(blank=True, help_text='Half-life of medication', max_length=100, null=True)),
                ('pregnancy_category', models.CharField(blank=True, help_text='FDA pregnancy category (A, B, C, D, X)', max_length=5, null=True)),
                ('pediatric_use', models.TextField(blank=True, help_text='Information for pediatric use', null=True)),
                ('geriatric_use', models.TextField(blank=True, help_text='Information for geriatric use', null=True)),
                ('monitoring_required', models.BooleanField(default=False, help_text='Whether medication requires special monitoring')),
                ('monitoring_parameters', models.TextField(blank=True, help_text='What to monitor during therapy', null=True)),
                ('high_alert_medication', models.BooleanField(default=False, help_text='Whether this is a high-alert medication with risk of harm')),
                ('risk_score', models.IntegerField(default=1, help_text='Risk score from 1-10 for AI prioritization', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_controlled_substance', models.BooleanField(default=False, help_text='Whether this is a controlled substance')),
                ('schedule', models.CharField(blank=True, help_text='Schedule for controlled substances', max_length=10, null=True)),
                ('requires_prior_auth', models.BooleanField(default=False, help_text='Whether insurance typically requires prior authorization')),
            ],
            options={
                'verbose_name': 'Medication Catalog',
                'verbose_name_plural': 'Medication Catalog',
                'indexes': [models.Index(fields=['generic_name'], name='api_medicat_generic_9e279b_idx'), models.Index(fields=['drug_class'], name='api_medicat_drug_cl_3174e6_idx'), models.Index(fields=['drug_code'], name='api_medicat_drug_co_4a4cbb_idx'), models.Index(fields=['is_controlled_substance'], name='api_medicat_is_cont_1758e6_idx'), models.Index(fields=['high_alert_medication'], name='api_medicat_high_al_e43081_idx')],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication_name', models.CharField(help_text='Name of medication as prescribed', max_length=255)),
                ('generic_name', models.CharField(blank=True, help_text='Generic name of medication', max_length=255)),
                ('ndc_code', models.CharField(blank=True, help_text='National Drug Code', max_length=50, null=True)),
                ('strength', models.CharField(help_text="Medication strength (e.g., '10 mg')", max_length=100)),
                ('form', models.CharField(help_text="Medication form (e.g., 'tablet', 'capsule')", max_length=100)),
                ('route', models.CharField(help_text="Route of administration (e.g., 'oral', 'topical')", max_length=100)),
                ('dosage', models.CharField(help_text="Dosage instructions (e.g., '1 tablet')", max_length=255)),
                ('frequency', models.CharField(help_text="Frequency of administration (e.g., 'twice daily')", max_length=255)),
                ('start_date', models.DateField(help_text='Date medication was started')),
                ('end_date', models.DateField(blank=True, help_text='Date medication should end (if not ongoing)', null=True)),
                ('is_ongoing', models.BooleanField(default=True, help_text='Whether medication is currently active')),
                ('duration', models.CharField(blank=True, help_text="Duration of therapy (e.g., '10 days', 'ongoing')", max_length=100, null=True)),
                ('patient_instructions', models.TextField(blank=True, help_text='Special instructions for patient', null=True)),
                ('pharmacy_instructions', models.TextField(blank=True, help_text='Special instructions for pharmacy', null=True)),
                ('indication', models.CharField(blank=True, help_text='Reason medication was prescribed', max_length=255, null=True)),
                ('diagnosis_code', models.CharField(blank=True, help_text='ICD-10 code for related diagnosis', max_length=20, null=True)),
                ('prescription_number', models.CharField(blank=True, help_text='Pharmacy prescription number', max_length=50, null=True)),
                ('refills_authorized', models.IntegerField(default=0, help_text='Number of refills authorized')),
                ('refills_remaining', models.IntegerField(default=0, help_text='Number of refills remaining')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued'), ('on_hold', 'On Hold'), ('never_administered', 'Never Administered')], default='active', help_text='Current status of medication', max_length=20)),
                ('pharmacy_name', models.CharField(blank=True, help_text='Dispensing pharmacy name', max_length=255, null=True)),
                ('priority', models.IntegerField(default=3, help_text='Priority level (1-5), where 1 is highest priority', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('side_effects_experienced', models.TextField(blank=True, help_text='Side effects reported by patient', null=True)),
                ('adherence', models.CharField(choices=[('good', 'Good'), ('moderate', 'Moderate'), ('poor', 'Poor'), ('unknown', 'Unknown')], default='unknown', help_text='Patient adherence to medication', max_length=20)),
                ('adherence_notes', models.TextField(blank=True, help_text='Notes about patient adherence', null=True)),
                ('discontinued_date', models.DateField(blank=True, help_text='Date medication was discontinued', null=True)),
                ('discontinuation_reason', models.CharField(blank=True, choices=[('completed', 'Course Completed'), ('adverse_effect', 'Adverse Effect'), ('ineffective', 'Not Effective'), ('cost', 'Cost Issues'), ('patient_choice', 'Patient Choice'), ('alternative', 'Alternative Treatment'), ('other', 'Other')], help_text='Reason for discontinuation', max_length=20, null=True)),
                ('discontinuation_notes', models.TextField(blank=True, help_text='Notes about medication discontinuation', null=True)),
                ('medical_record', models.ForeignKey(help_text='Medical record this medication belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='api.medicalrecord')),
                ('prescribed_by', models.ForeignKey(help_text='Provider who prescribed the medication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medications', to='api.doctor')),
                ('catalog_entry', models.ForeignKey(blank=True, help_text='Reference to catalog information', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='api.medicationcatalog')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['medical_record', 'medication_name'], name='api_medicat_medical_ceb832_idx'), models.Index(fields=['medical_record', 'status'], name='api_medicat_medical_40c9dd_idx'), models.Index(fields=['start_date'], name='api_medicat_start_d_6d4574_idx'), models.Index(fields=['is_ongoing'], name='api_medicat_is_ongo_4108c6_idx')],
            },
        ),
    ]
