# Generated by Django 5.0.1 on 2025-05-06 19:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_medicationcatalog_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Name of imaging type (e.g., 'X-Ray', 'MRI')", max_length=255)),
                ('code', models.CharField(help_text='Unique code for imaging type', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Description of this imaging type')),
                ('preparation_instructions', models.TextField(blank=True, help_text='Patient preparation instructions', null=True)),
                ('uses_radiation', models.BooleanField(default=False, help_text='Whether this imaging type uses ionizing radiation')),
                ('uses_contrast', models.BooleanField(default=False, help_text='Whether this imaging type typically uses contrast')),
                ('typical_duration', models.CharField(blank=True, help_text='Typical duration of procedure', max_length=100, null=True)),
                ('contraindications', models.TextField(blank=True, help_text='Contraindications for this imaging type', null=True)),
                ('risks', models.TextField(blank=True, help_text='Risks associated with this imaging type', null=True)),
            ],
            options={
                'verbose_name': 'Imaging Type',
                'verbose_name_plural': 'Imaging Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_date', models.DateTimeField(help_text='Date and time when imaging was performed')),
                ('accession_number', models.CharField(blank=True, help_text="Medical facility's accession number", max_length=100, null=True)),
                ('study_uid', models.CharField(blank=True, help_text='DICOM Study Instance UID if available', max_length=255, null=True)),
                ('body_region', models.CharField(choices=[('head', 'Head'), ('neck', 'Neck'), ('chest', 'Chest/Thorax'), ('abdomen', 'Abdomen'), ('pelvis', 'Pelvis'), ('spine', 'Spine'), ('upper_extremity', 'Upper Extremity'), ('lower_extremity', 'Lower Extremity'), ('whole_body', 'Whole Body'), ('other', 'Other')], help_text='Body region imaged', max_length=20)),
                ('body_part_detail', models.CharField(blank=True, help_text="Specific body part detail (e.g., 'Left Knee')", max_length=255, null=True)),
                ('laterality', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('bilateral', 'Bilateral'), ('not_applicable', 'Not Applicable')], help_text='Laterality of body part if applicable', max_length=20, null=True)),
                ('facility', models.CharField(help_text='Facility where imaging was performed', max_length=255)),
                ('with_contrast', models.BooleanField(default=False, help_text='Whether contrast was used')),
                ('contrast_type', models.CharField(blank=True, help_text='Type of contrast used if applicable', max_length=255, null=True)),
                ('procedure_notes', models.TextField(blank=True, help_text='Notes about the procedure', null=True)),
                ('clinical_indication', models.TextField(help_text='Clinical reason for the imaging')),
                ('findings', models.TextField(blank=True, help_text='Findings from the imaging', null=True)),
                ('impression', models.TextField(blank=True, help_text="Radiologist's impression", null=True)),
                ('result', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical Abnormality'), ('inconclusive', 'Inconclusive'), ('pending', 'Pending Interpretation')], default='pending', help_text='Overall result of imaging', max_length=20)),
                ('structured_findings', models.JSONField(blank=True, default=dict, help_text='Structured findings in JSON format', null=True)),
                ('interpreted_by', models.CharField(blank=True, help_text='Name of radiologist who interpreted the image', max_length=255, null=True)),
                ('interpretation_date', models.DateTimeField(blank=True, help_text='Date and time of interpretation', null=True)),
                ('image_file', models.FileField(blank=True, help_text='Actual image file if stored directly', null=True, upload_to='medical_images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'dcm', 'dicom'])])),
                ('pacs_link', models.URLField(blank=True, help_text='Link to image in PACS system', null=True)),
                ('series_count', models.IntegerField(default=1, help_text='Number of series in this study')),
                ('image_count', models.IntegerField(default=1, help_text='Total number of images in this study')),
                ('requires_followup', models.BooleanField(default=False, help_text='Whether follow-up imaging is recommended')),
                ('followup_notes', models.TextField(blank=True, help_text='Notes about recommended follow-up', null=True)),
                ('followup_date', models.DateField(blank=True, help_text='Recommended date for follow-up imaging', null=True)),
                ('ai_analyzed', models.BooleanField(default=False, help_text='Whether image has been analyzed by AI')),
                ('ai_findings', models.JSONField(blank=True, default=dict, help_text='AI analysis results in JSON format', null=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score (0-1)', max_digits=5, null=True)),
                ('imaging_type', models.ForeignKey(help_text='Type of medical image', on_delete=django.db.models.deletion.PROTECT, related_name='images', to='api.imagingtype')),
                ('medical_record', models.ForeignKey(help_text='Medical record this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='medical_images', to='api.medicalrecord')),
                ('ordered_by', models.ForeignKey(help_text='Doctor who ordered the imaging', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_images', to='api.doctor')),
            ],
            options={
                'verbose_name': 'Medical Image',
                'verbose_name_plural': 'Medical Images',
                'ordering': ['-study_date'],
                'indexes': [models.Index(fields=['medical_record', 'study_date'], name='api_medical_medical_c27b06_idx'), models.Index(fields=['imaging_type'], name='api_medical_imaging_648066_idx'), models.Index(fields=['body_region'], name='api_medical_body_re_35f10a_idx'), models.Index(fields=['result'], name='api_medical_result_3c602d_idx')],
            },
        ),
    ]
