# Generated by Django 5.0.1 on 2025-05-03 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_appointmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='api.appointmentfee'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('partial', 'Partial Payment'), ('completed', 'Payment Completed'), ('waived', 'Payment Waived'), ('insurance', 'Insurance Processing'), ('refunded', 'Refunded')], default='waived', max_length=20),
        ),
    ]
