# Generated by Django 5.0.1 on 2025-05-04 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_appointment_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Record Access Log',
                'verbose_name_plural': 'Medical Record Access Logs',
                'ordering': ['-access_time'],
            },
        ),
    ]
