# Generated by Django 5.0.1 on 2025-05-06 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_imagingtype_medicalimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_role', models.CharField(help_text="Role of the author (e.g., 'Physician', 'Nurse')", max_length=100)),
                ('note_type', models.CharField(choices=[('progress', 'Progress Note'), ('admission', 'Admission Note'), ('discharge', 'Discharge Summary'), ('consultation', 'Consultation Note'), ('procedure', 'Procedure Note'), ('operative', 'Operative Report'), ('emergency', 'Emergency Department Note'), ('history_physical', 'History and Physical'), ('soap', 'SOAP Note'), ('nursing', 'Nursing Note'), ('medication', 'Medication Note'), ('therapy', 'Therapy Note'), ('social_work', 'Social Work Note'), ('nutrition', 'Nutrition Note'), ('mental_health', 'Mental Health Note'), ('phone', 'Phone Communication'), ('referral', 'Referral Note'), ('transfer', 'Transfer Note'), ('other', 'Other')], help_text='Type of clinical note', max_length=50)),
                ('note_date', models.DateTimeField(help_text='Date and time of the note')),
                ('visit_date', models.DateField(blank=True, help_text='Date of associated visit or encounter', null=True)),
                ('title', models.CharField(help_text='Title of the note', max_length=255)),
                ('content', models.TextField(help_text='Full text content of the note')),
                ('structured_content', models.JSONField(blank=True, default=dict, help_text='Structured content organized by sections', null=True)),
                ('encounter_type', models.CharField(blank=True, help_text="Type of encounter (e.g., 'Office Visit', 'Telemedicine')", max_length=100, null=True)),
                ('location', models.CharField(blank=True, help_text='Location where care was provided', max_length=255, null=True)),
                ('chief_complaint', models.TextField(blank=True, help_text="Patient's chief complaint", null=True)),
                ('diagnoses', models.JSONField(blank=True, default=list, help_text='List of diagnoses addressed in this note', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('amended', 'Amended'), ('deleted', 'Deleted')], default='draft', help_text='Status of the clinical note', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Version number of the note')),
                ('amendment_reason', models.TextField(blank=True, help_text='Reason for amendment if this is an amended note', null=True)),
                ('is_private', models.BooleanField(default=False, help_text='Whether note contains sensitive information with restricted access')),
                ('nlp_processed', models.BooleanField(default=False, help_text='Whether natural language processing has been applied')),
                ('nlp_entities', models.JSONField(blank=True, default=list, help_text='Entities extracted through NLP', null=True)),
                ('nlp_concepts', models.JSONField(blank=True, default=list, help_text='Medical concepts identified through NLP', null=True)),
                ('signed', models.BooleanField(default=False, help_text='Whether the note has been signed')),
                ('signed_at', models.DateTimeField(blank=True, help_text='Date and time the note was signed', null=True)),
                ('cosigned_at', models.DateTimeField(blank=True, help_text='Date and time the note was cosigned', null=True)),
                ('author', models.ForeignKey(help_text='Healthcare provider who authored the note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
                ('cosigned_by', models.ForeignKey(blank=True, help_text='Provider who cosigned the note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cosigned_notes', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(help_text='Medical record this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='api.medicalrecord')),
                ('previous_version', models.ForeignKey(blank=True, help_text='Reference to previous version of this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='api.clinicalnote')),
                ('signed_by', models.ForeignKey(blank=True, help_text='Provider who signed the note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinical Note',
                'verbose_name_plural': 'Clinical Notes',
                'ordering': ['-note_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthcareProviderNote',
            fields=[
                ('clinicalnote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.clinicalnote')),
                ('billing_code', models.CharField(blank=True, help_text='Billing or CPT code associated with this note', max_length=50, null=True)),
                ('complexity_level', models.CharField(blank=True, choices=[('low', 'Low Complexity'), ('moderate', 'Moderate Complexity'), ('high', 'High Complexity')], help_text='Level of complexity for billing purposes', max_length=20, null=True)),
                ('time_spent', models.IntegerField(blank=True, help_text='Time spent with patient in minutes', null=True)),
                ('assessment_and_plan', models.TextField(blank=True, help_text='Assessment and plan section', null=True)),
                ('physical_examination', models.TextField(blank=True, help_text='Physical examination findings', null=True)),
                ('medical_decision_making', models.TextField(blank=True, help_text='Medical decision making documentation', null=True)),
                ('procedures_performed', models.JSONField(blank=True, default=list, help_text='Procedures performed during visit', null=True)),
            ],
            options={
                'verbose_name': 'Provider Note',
                'verbose_name_plural': 'Provider Notes',
            },
            bases=('api.clinicalnote',),
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('clinicalnote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.clinicalnote')),
                ('nursing_assessment', models.TextField(blank=True, help_text='Nursing assessment', null=True)),
                ('interventions', models.TextField(blank=True, help_text='Nursing interventions performed', null=True)),
                ('patient_response', models.TextField(blank=True, help_text="Patient's response to interventions", null=True)),
                ('nursing_care_plan', models.TextField(blank=True, help_text='Nursing care plan', null=True)),
                ('intake_output', models.JSONField(blank=True, default=dict, help_text='Intake and output measurements', null=True)),
                ('adl_status', models.TextField(blank=True, help_text='Activities of daily living status', null=True)),
            ],
            options={
                'verbose_name': 'Nursing Note',
                'verbose_name_plural': 'Nursing Notes',
            },
            bases=('api.clinicalnote',),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['medical_record', 'note_date'], name='api_clinica_medical_71d240_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['note_type'], name='api_clinica_note_ty_5bf9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['author'], name='api_clinica_author__2a6175_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['status'], name='api_clinica_status_4c3700_idx'),
        ),
    ]
