# Generated by Django 5.0.1 on 2025-05-06 19:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_clinicalnote_healthcareprovidernote_nursingnote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diet_type', models.CharField(blank=True, choices=[('regular', 'Regular/No Restrictions'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free'), ('ketogenic', 'Ketogenic'), ('paleo', 'Paleo'), ('mediterranean', 'Mediterranean'), ('low_carb', 'Low Carbohydrate'), ('low_fat', 'Low Fat'), ('low_sodium', 'Low Sodium'), ('diabetic', 'Diabetic'), ('renal', 'Renal/Kidney'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('other', 'Other')], help_text='Primary diet type', max_length=20, null=True)),
                ('diet_details', models.TextField(blank=True, help_text='Additional details about diet', null=True)),
                ('daily_meals', models.IntegerField(blank=True, help_text='Typical number of meals per day', null=True)),
                ('food_allergies', models.TextField(blank=True, help_text='Food allergies or intolerances', null=True)),
                ('nutrition_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('unknown', 'Unknown')], default='unknown', help_text='Overall nutrition quality assessment', max_length=20)),
                ('fruit_vegetable_servings', models.IntegerField(blank=True, help_text='Average daily fruit and vegetable servings', null=True)),
                ('exercise_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('several_times_week', 'Several Times per Week'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('rarely', 'Rarely'), ('never', 'Never')], help_text='Frequency of exercise', max_length=20, null=True)),
                ('exercise_duration', models.IntegerField(blank=True, help_text='Average exercise duration in minutes', null=True)),
                ('exercise_types', models.JSONField(blank=True, default=list, help_text='Types of exercise regularly performed', null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active'), ('extremely_active', 'Extremely Active')], help_text='Overall physical activity level', max_length=20, null=True)),
                ('average_sleep_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Average hours of sleep per night', max_digits=3, null=True)),
                ('sleep_quality', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], help_text='Subjective sleep quality', max_length=20, null=True)),
                ('sleep_disorders', models.TextField(blank=True, help_text='Known sleep disorders', null=True)),
                ('tobacco_use', models.CharField(blank=True, choices=[('never', 'Never'), ('former', 'Former'), ('current', 'Current')], help_text='Tobacco use status', max_length=20, null=True)),
                ('tobacco_type', models.CharField(blank=True, help_text='Type of tobacco used (e.g., cigarettes, e-cigarettes, pipe)', max_length=100, null=True)),
                ('tobacco_frequency', models.CharField(blank=True, help_text='Frequency of tobacco use', max_length=100, null=True)),
                ('tobacco_start_age', models.IntegerField(blank=True, help_text='Age started using tobacco', null=True)),
                ('tobacco_quit_age', models.IntegerField(blank=True, help_text='Age quit using tobacco if former user', null=True)),
                ('tobacco_pack_years', models.DecimalField(blank=True, decimal_places=2, help_text='Pack-years for cigarette smokers', max_digits=5, null=True)),
                ('alcohol_use', models.CharField(blank=True, choices=[('never', 'Never'), ('former', 'Former'), ('occasional', 'Occasional'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], help_text='Alcohol use status', max_length=20, null=True)),
                ('alcohol_frequency', models.CharField(blank=True, help_text='Frequency of alcohol consumption', max_length=100, null=True)),
                ('alcohol_drinks_per_week', models.IntegerField(blank=True, help_text='Average alcoholic drinks per week', null=True)),
                ('alcohol_quit_age', models.IntegerField(blank=True, help_text='Age quit using alcohol if former user', null=True)),
                ('recreational_drug_use', models.CharField(blank=True, choices=[('never', 'Never'), ('former', 'Former'), ('current', 'Current')], help_text='Recreational drug use status', max_length=20, null=True)),
                ('recreational_drugs', models.JSONField(blank=True, default=list, help_text='Types of recreational drugs used', null=True)),
                ('caffeine_use', models.CharField(blank=True, choices=[('none', 'None'), ('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], help_text='Caffeine consumption level', max_length=20, null=True)),
                ('caffeine_drinks_per_day', models.IntegerField(blank=True, help_text='Average caffeinated drinks per day', null=True)),
                ('occupation', models.CharField(blank=True, help_text='Current or most recent occupation', max_length=255, null=True)),
                ('occupation_category', models.CharField(blank=True, help_text='Category of occupation', max_length=100, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('self_employed', 'Self-employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('disabled', 'Unable to work due to disability'), ('student', 'Student'), ('homemaker', 'Homemaker')], help_text='Current employment status', max_length=50, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('none', 'No formal education'), ('primary', 'Primary/Elementary'), ('secondary', 'Secondary/High School'), ('vocational', 'Vocational/Technical'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctoral', 'Doctoral Degree'), ('professional', 'Professional Degree')], help_text='Highest level of education completed', max_length=50, null=True)),
                ('occupational_hazards', models.TextField(blank=True, help_text='Occupational hazards or exposures', null=True)),
                ('housing_type', models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('assisted_living', 'Assisted Living'), ('nursing_home', 'Nursing Home'), ('homeless', 'Homeless'), ('group_home', 'Group Home'), ('other', 'Other')], help_text='Type of housing', max_length=50, null=True)),
                ('household_members', models.IntegerField(blank=True, help_text='Number of people in household', null=True)),
                ('living_arrangement', models.CharField(blank=True, choices=[('alone', 'Lives Alone'), ('family', 'Lives with Family'), ('roommates', 'Lives with Roommates'), ('spouse', 'Lives with Spouse/Partner'), ('caregiver', 'Lives with Caregiver'), ('other', 'Other')], help_text='Living arrangement', max_length=50, null=True)),
                ('dependents', models.IntegerField(blank=True, help_text='Number of dependents', null=True)),
                ('income_range', models.CharField(blank=True, choices=[('low', 'Low Income'), ('lower_middle', 'Lower Middle Income'), ('middle', 'Middle Income'), ('upper_middle', 'Upper Middle Income'), ('high', 'High Income'), ('decline', 'Decline to Answer')], help_text='Income range', max_length=50, null=True)),
                ('financial_strain', models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], help_text='Level of financial strain', max_length=20, null=True)),
                ('insurance_status', models.CharField(blank=True, choices=[('private', 'Private Insurance'), ('public', 'Public Insurance'), ('military', 'Military Insurance'), ('none', 'No Insurance'), ('multiple', 'Multiple')], help_text='Health insurance status', max_length=50, null=True)),
                ('has_regular_healthcare', models.BooleanField(blank=True, help_text='Whether patient has regular access to healthcare', null=True)),
                ('transportation_access', models.CharField(blank=True, choices=[('own_vehicle', 'Own Vehicle'), ('public', 'Public Transportation'), ('rides_others', 'Rides from Others'), ('medical_transport', 'Medical Transportation'), ('limited', 'Limited Transportation'), ('none', 'No Transportation')], help_text='Primary mode of transportation', max_length=50, null=True)),
                ('distance_to_healthcare', models.IntegerField(blank=True, help_text='Distance to nearest healthcare facility in kilometers', null=True)),
                ('environmental_exposures', models.JSONField(blank=True, default=list, help_text='Environmental exposures or hazards', null=True)),
                ('neighborhood_safety', models.CharField(blank=True, choices=[('very_safe', 'Very Safe'), ('safe', 'Safe'), ('neutral', 'Neutral'), ('unsafe', 'Unsafe'), ('very_unsafe', 'Very Unsafe')], help_text='Perception of neighborhood safety', max_length=20, null=True)),
                ('access_to_healthy_food', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], help_text='Access to healthy food options', max_length=20, null=True)),
                ('stress_level', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], help_text='Self-reported stress level', max_length=20, null=True)),
                ('social_support', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('none', 'None')], help_text='Level of social support', max_length=20, null=True)),
                ('spiritual_religious', models.CharField(blank=True, help_text='Spiritual or religious practices if relevant to health', max_length=100, null=True)),
                ('preventive_care', models.CharField(blank=True, choices=[('regular', 'Regular'), ('occasional', 'Occasional'), ('rare', 'Rare'), ('never', 'Never')], help_text='Frequency of preventive healthcare visits', max_length=20, null=True)),
                ('medication_adherence', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('not_applicable', 'Not Applicable')], help_text='Level of medication adherence', max_length=20, null=True)),
                ('health_literacy', models.CharField(blank=True, choices=[('high', 'High'), ('adequate', 'Adequate'), ('limited', 'Limited'), ('low', 'Low'), ('unknown', 'Unknown')], help_text='Assessment of health literacy', max_length=20, null=True)),
                ('internet_access', models.CharField(blank=True, choices=[('reliable', 'Reliable'), ('limited', 'Limited'), ('none', 'None')], help_text='Level of internet access', max_length=20, null=True)),
                ('uses_health_apps', models.BooleanField(blank=True, help_text='Whether patient uses health apps', null=True)),
                ('telehealth_capable', models.BooleanField(blank=True, help_text='Whether patient has capability for telehealth visits', null=True)),
                ('wearable_devices', models.JSONField(blank=True, default=list, help_text='Health wearables used (e.g., fitness tracker, CGM)', null=True)),
                ('lifestyle_risk_assessment', models.JSONField(blank=True, default=dict, help_text='Computed risk assessment based on lifestyle factors', null=True)),
                ('additional_info', models.TextField(blank=True, help_text='Additional lifestyle information not captured elsewhere', null=True)),
                ('last_updated_by', models.ForeignKey(help_text='User who last updated this information', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lifestyle_information', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.OneToOneField(help_text='Medical record this lifestyle information belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_information', to='api.medicalrecord')),
            ],
            options={
                'verbose_name': 'Lifestyle Information',
                'verbose_name_plural': 'Lifestyle Information',
                'indexes': [models.Index(fields=['medical_record'], name='api_lifesty_medical_5dfdf9_idx'), models.Index(fields=['tobacco_use'], name='api_lifesty_tobacco_72bf62_idx'), models.Index(fields=['alcohol_use'], name='api_lifesty_alcohol_f1ec93_idx'), models.Index(fields=['employment_status'], name='api_lifesty_employm_881138_idx')],
            },
        ),
    ]
