# Generated by Django 5.0.1 on 2025-05-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appointment_medical_summary'),
        ('api', '0010_lifestyleinformation'),
    ]

    operations = [
    ]
