# Generated by Django 5.0.1 on 2025-05-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20250508_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='medical_summary',
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms_data',
            field=models.JSONField(default=list, help_text='Structured symptoms data'),
        ),
        migrations.AddField(
            model_name='medication',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Appointment during which this medication was prescribed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='api.appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='api.doctor'),
        ),
    ]
