# Generated by Django 5.0.1 on 2025-05-14 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20250508_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='medical_summary',
        ),
        migrations.AddField(
            model_name='hospitaladmin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hospitaladmin',
            name='last_password_change',
            field=models.DateTimeField(blank=True, help_text='When the admin last changed their password', null=True),
        ),
        migrations.AddField(
            model_name='hospitaladmin',
            name='password_change_required',
            field=models.BooleanField(default=True, help_text='Whether the admin must change their password on next login'),
        ),
    ]
