# Generated by Django 5.0.1 on 2025-05-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_appointment_medical_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaladmin',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='The real email address for communications', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaladmin',
            name='email',
            field=models.EmailField(help_text='The admin username used for login (not a real email inbox)', max_length=254, unique=True),
        ),
    ]
