# Generated by Django 5.0.1 on 2025-05-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_appointment_to_medication'),
        ('api', '0013_hospitaladmin_contact_email_and_more'),
    ]

    operations = [
    ]
