# Generated by Django 5.0.1 on 2025-05-23 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20250523_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptoms_data',
            field=models.JSONField(default=list, help_text='Structured symptoms data'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='api.doctor'),
        ),
    ]
