# Generated by Django 5.0.1 on 2025-05-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_appointment_symptoms_data_alter_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='last_password_change',
        ),
        migrations.AlterField(
            model_name='hospitaladmin',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Real email for receiving notifications', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaladmin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='hospitaladmin',
            name='password_change_required',
            field=models.BooleanField(default=False, help_text='Flag to force password change on next login'),
        ),
    ]
