# Generated by Django 5.0.1 on 2025-05-29 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_hospitaladmin_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_id', models.CharField(help_text='Unique admission identifier', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Admission'), ('admitted', 'Currently Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('deceased', 'Deceased'), ('left_ama', 'Left Against Medical Advice')], default='pending', help_text='Current admission status', max_length=20)),
                ('admission_type', models.CharField(choices=[('inpatient', 'Inpatient'), ('observation', 'Observation'), ('day_case', 'Day Case'), ('respite', 'Respite Care')], default='inpatient', help_text='Type of admission', max_length=20)),
                ('priority', models.CharField(choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('elective', 'Elective')], default='elective', help_text='Admission priority', max_length=20)),
                ('reason_for_admission', models.TextField(help_text='Primary reason for hospital admission')),
                ('is_icu_bed', models.BooleanField(default=False, help_text='Whether patient is in ICU bed')),
                ('bed_identifier', models.CharField(blank=True, help_text='Bed identifier (e.g., Room 101-A)', max_length=20, null=True)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When patient was admitted')),
                ('expected_discharge_date', models.DateTimeField(blank=True, help_text='Expected discharge date', null=True)),
                ('actual_discharge_date', models.DateTimeField(blank=True, help_text='Actual discharge date', null=True)),
                ('length_of_stay_days', models.PositiveIntegerField(blank=True, help_text='Length of stay in days (calculated on discharge)', null=True)),
                ('diagnosis', models.TextField(blank=True, help_text='Primary diagnosis')),
                ('secondary_diagnoses', models.TextField(blank=True, help_text='Secondary diagnoses')),
                ('acuity_level', models.PositiveSmallIntegerField(default=3, help_text='Patient acuity level (1-5, with 5 being highest acuity)')),
                ('isolation_required', models.BooleanField(default=False, help_text='Whether patient requires isolation')),
                ('isolation_type', models.CharField(blank=True, help_text='Type of isolation if required', max_length=50)),
                ('discharge_destination', models.CharField(blank=True, help_text='Where patient was discharged to', max_length=100)),
                ('discharge_summary', models.TextField(blank=True, help_text='Summary of stay and discharge instructions')),
                ('followup_instructions', models.TextField(blank=True, help_text='Follow-up care instructions')),
                ('insurance_information', models.JSONField(blank=True, default=dict, help_text='Insurance details for this admission')),
                ('admission_notes', models.TextField(blank=True, help_text='Administrative notes about this admission')),
                ('attending_doctor', models.ForeignKey(help_text='Primary doctor responsible for this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_admissions', to='api.doctor')),
                ('consulting_doctors', models.ManyToManyField(blank=True, help_text='Other doctors consulting on this case', related_name='consulting_admissions', to='api.doctor')),
                ('department', models.ForeignKey(help_text='Department where patient is admitted', on_delete=django.db.models.deletion.PROTECT, related_name='patient_admissions', to='api.department')),
                ('hospital', models.ForeignKey(help_text='Hospital where patient is admitted', on_delete=django.db.models.deletion.PROTECT, related_name='patient_admissions', to='api.hospital')),
                ('patient', models.ForeignKey(help_text='Patient being admitted', on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When transfer occurred')),
                ('reason', models.TextField(blank=True, help_text='Reason for transfer')),
                ('admission', models.ForeignKey(help_text='The admission being transferred', on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='api.patientadmission')),
                ('from_department', models.ForeignKey(help_text='Department transferring from', on_delete=django.db.models.deletion.PROTECT, related_name='patient_transfers_out', to='api.department')),
                ('to_department', models.ForeignKey(help_text='Department transferring to', on_delete=django.db.models.deletion.PROTECT, related_name='patient_transfers_in', to='api.department')),
            ],
            options={
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['admission_id'], name='api_patient_admissi_87ba2f_idx'),
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['patient'], name='api_patient_patient_7d4319_idx'),
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['status'], name='api_patient_status_66387d_idx'),
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['hospital', 'department'], name='api_patient_hospita_aba593_idx'),
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['admission_date'], name='api_patient_admissi_d65cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['attending_doctor'], name='api_patient_attendi_9a6e3c_idx'),
        ),
    ]
