# Generated by Django 5.0.1 on 2025-05-29 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_patientadmission_patienttransfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='is_registered_patient',
            field=models.BooleanField(default=True, help_text='Whether the patient was registered with the hospital before admission'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='registration_status',
            field=models.CharField(choices=[('complete', 'Complete Registration'), ('partial', 'Partial Registration'), ('pending', 'Registration Pending')], default='complete', help_text='Status of patient registration', max_length=20),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='temp_patient_details',
            field=models.JSONField(blank=True, help_text='Temporary details for unregistered patients', null=True),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='temp_patient_id',
            field=models.CharField(blank=True, help_text='Temporary ID for unregistered patients', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient being admitted', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
