# Generated by Django 5.0.1 on 2025-06-03 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_patientadmission_is_registered_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='referred_to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_appointments', to='api.department'),
        ),
    ]
