# Generated by Django 5.0.1 on 2025-06-04 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_appointment_referred_to_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='referred_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_to', to='api.appointment'),
        ),
    ]
