# Generated by Django 5.0.1 on 2025-06-09 21:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_referred_from_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('secure_filename', models.CharField(max_length=255, unique=True)),
                ('file_extension', models.CharField(max_length=10)),
                ('file_type', models.CharField(max_length=20)),
                ('file_size', models.PositiveIntegerField()),
                ('encryption_key_id', models.CharField(max_length=32)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('virus_scanned', models.BooleanField(default=False)),
                ('security_score', models.PositiveIntegerField(default=0)),
                ('vault_path', models.CharField(max_length=500)),
                ('storage_backend', models.CharField(default='local_vault', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('doctor', 'Doctor Access'), ('appointment', 'Appointment Specific'), ('temporary', 'Temporary Link'), ('emergency', 'Emergency Access')], max_length=20)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('allowed_email', models.EmailField(blank=True, max_length=254)),
                ('max_accesses', models.PositiveIntegerField(default=1)),
                ('current_accesses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.securedocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'File Upload'), ('view', 'File View'), ('download', 'File Download'), ('share', 'File Share'), ('delete', 'File Delete'), ('access_denied', 'Access Denied')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='api.securedocument')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='securedocument',
            index=models.Index(fields=['user', 'created_at'], name='api_secured_user_id_ac46d4_idx'),
        ),
        migrations.AddIndex(
            model_name='securedocument',
            index=models.Index(fields=['file_id'], name='api_secured_file_id_9b40cc_idx'),
        ),
        migrations.AddIndex(
            model_name='securedocument',
            index=models.Index(fields=['user', 'is_active'], name='api_secured_user_id_f8eaf4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['share_token'], name='api_documen_share_t_a6aa59_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['document', 'is_active'], name='api_documen_documen_b0c9d6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['expires_at', 'is_active'], name='api_documen_expires_c10ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['document', 'timestamp'], name='api_documen_documen_0ddf68_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['user', 'timestamp'], name='api_documen_user_id_db4777_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['action', 'timestamp'], name='api_documen_action_62a03f_idx'),
        ),
    ]
