# Generated by Django 5.0.1 on 2025-06-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_securedocument_documentshare_documentaccesslog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Associated appointment (optional for payment-first flow)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.appointment'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Associated hospital (optional for payment-first flow)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.hospital'),
        ),
    ]
