# Generated by Django 5.0.1 on 2025-06-24 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_paymenttransaction_appointment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date'], 'permissions': [('can_approve_appointments', 'Can approve appointments'), ('can_refer_appointments', 'Can refer appointments'), ('can_view_all_appointments', 'Can view all appointments')]},
        ),
        migrations.CreateModel(
            name='AppointmentMedicalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('medical_records', 'Medical Records Only'), ('documents', 'Documents Only'), ('full_access', 'Medical Records + Documents')], default='full_access', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Access Requested'), ('granted', 'Access Granted'), ('denied', 'Access Denied'), ('expired', 'Access Expired'), ('revoked', 'Access Revoked')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('request_reason', models.TextField(blank=True, help_text="Doctor's reason for requesting access")),
                ('patient_notes', models.TextField(blank=True, help_text="Patient's notes when granting/denying access")),
                ('first_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_access', to='api.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_medical_access', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_medical_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAccessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('access_requested', 'Access Requested'), ('access_granted', 'Access Granted'), ('access_denied', 'Access Denied'), ('access_revoked', 'Access Revoked'), ('record_accessed', 'Medical Record Accessed'), ('document_accessed', 'Document Accessed'), ('access_expired', 'Access Expired')], max_length=20)),
                ('event_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('medical_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.appointmentmedicalaccess')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='appointmentmedicalaccess',
            index=models.Index(fields=['appointment', 'status'], name='api_appoint_appoint_62b742_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentmedicalaccess',
            index=models.Index(fields=['doctor', 'status'], name='api_appoint_doctor__0cbb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentmedicalaccess',
            index=models.Index(fields=['patient', 'status'], name='api_appoint_patient_c98a43_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentmedicalaccess',
            index=models.Index(fields=['access_token'], name='api_appoint_access__50f64d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentmedicalaccess',
            index=models.Index(fields=['expires_at'], name='api_appoint_expires_049f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalaccessauditlog',
            index=models.Index(fields=['medical_access', 'event_type'], name='api_medical_medical_8f32fc_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalaccessauditlog',
            index=models.Index(fields=['event_timestamp'], name='api_medical_event_t_04d378_idx'),
        ),
    ]
