# Generated by Django 5.0.1 on 2025-06-26 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_customuser_womens_health_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_conditions', models.JSONField(blank=True, default=list, help_text='List of current medical conditions')),
                ('medications', models.JSONField(blank=True, default=list, help_text='List of current medications with dosage and frequency')),
                ('allergies', models.JSONField(blank=True, default=list, help_text='List of known allergies')),
                ('family_history', models.JSONField(blank=True, default=dict, help_text='Family medical history by condition')),
                ('surgical_history', models.JSONField(blank=True, default=list, help_text='List of previous surgeries and procedures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_medical_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extended Medical History',
                'verbose_name_plural': 'Extended Medical Histories',
            },
        ),
    ]
