# Generated by Django 5.0.1 on 2025-06-27 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_medicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideline_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('title', models.CharField(help_text='Title of the clinical guideline', max_length=300)),
                ('description', models.TextField(help_text='Detailed description of the guideline')),
                ('version', models.CharField(default='1.0', help_text='Version number of the guideline', max_length=20)),
                ('category', models.CharField(choices=[('emergency', 'Emergency Protocols'), ('surgery', 'Surgical Procedures'), ('medication', 'Medication Guidelines'), ('diagnosis', 'Diagnostic Protocols'), ('treatment', 'Treatment Plans'), ('prevention', 'Preventive Care'), ('infection_control', 'Infection Control'), ('patient_safety', 'Patient Safety'), ('quality_assurance', 'Quality Assurance'), ('maternity', 'Maternity Care'), ('pediatric', 'Pediatric Care'), ('geriatric', 'Geriatric Care'), ('mental_health', 'Mental Health'), ('oncology', 'Oncology'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('radiology', 'Radiology'), ('laboratory', 'Laboratory Procedures'), ('nursing', 'Nursing Protocols'), ('other', 'Other')], help_text='Category of the clinical guideline', max_length=30)),
                ('specialty', models.CharField(blank=True, help_text='Medical specialty this guideline applies to', max_length=100, null=True)),
                ('keywords', models.JSONField(default=list, help_text='Search keywords for this guideline')),
                ('content_type', models.CharField(choices=[('pdf', 'PDF Document'), ('text', 'Text Content'), ('mixed', 'Mixed Content')], default='pdf', max_length=20)),
                ('text_content', models.TextField(blank=True, help_text='Text content of the guideline', null=True)),
                ('effective_date', models.DateField(help_text='Date when this guideline becomes effective')),
                ('expiry_date', models.DateField(blank=True, help_text='Date when this guideline expires (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this guideline is currently active')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this guideline is published and visible to staff')),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Date and time when this guideline was approved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times this guideline has been accessed')),
                ('target_roles', models.JSONField(default=list, help_text="List of roles this guideline is intended for (e.g., ['doctor', 'nurse'])")),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('critical', 'Critical')], default='medium', help_text='Priority level of this guideline', max_length=10)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Administrator who approved this guideline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_guidelines', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Hospital admin who created this guideline', on_delete=django.db.models.deletion.CASCADE, related_name='created_guidelines', to=settings.AUTH_USER_MODEL)),
                ('file_document', models.ForeignKey(blank=True, help_text='Uploaded file document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.securedocument')),
                ('organization', models.ForeignKey(help_text='Hospital that owns this guideline', on_delete=django.db.models.deletion.CASCADE, related_name='clinical_guidelines', to='api.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuidelineAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('download', 'Downloaded'), ('shared', 'Shared'), ('printed', 'Printed'), ('bookmarked', 'Bookmarked')], help_text='Type of access action performed', max_length=20)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which the access occurred')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information')),
                ('session_duration', models.PositiveIntegerField(blank=True, help_text='Duration of access session in seconds', null=True)),
                ('department', models.CharField(blank=True, help_text='Department from which access occurred', max_length=100)),
                ('device_type', models.CharField(blank=True, help_text='Type of device used (mobile, desktop, tablet)', max_length=50)),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='api.clinicalguideline')),
                ('user', models.ForeignKey(help_text='User who accessed the guideline', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='GuidelineBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this guideline')),
                ('is_active', models.BooleanField(default=True)),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='api.clinicalguideline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guideline_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bookmarked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clinicalguideline',
            index=models.Index(fields=['organization', 'is_active'], name='api_clinica_organiz_a4a6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalguideline',
            index=models.Index(fields=['category', 'specialty'], name='api_clinica_categor_1e5a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalguideline',
            index=models.Index(fields=['approval_status', 'is_published'], name='api_clinica_approva_8d2b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalguideline',
            index=models.Index(fields=['effective_date', 'expiry_date'], name='api_clinica_effecti_7c3e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalguideline',
            index=models.Index(fields=['created_at'], name='api_clinica_created_2f1d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalguideline',
            index=models.Index(fields=['guideline_id'], name='api_clinica_guideli_5a4b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='guidelineaccess',
            index=models.Index(fields=['guideline', 'accessed_at'], name='api_guideli_guideli_9e6f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='guidelineaccess',
            index=models.Index(fields=['user', 'accessed_at'], name='api_guideli_user_id_3b2c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='guidelineaccess',
            index=models.Index(fields=['action', 'accessed_at'], name='api_guideli_action_7a8c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='guidelineaccess',
            index=models.Index(fields=['guideline', 'user'], name='api_guideli_guideli_4f5a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='guidelinebookmark',
            index=models.Index(fields=['user', 'is_active'], name='api_guideli_user_id_8c9d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='guidelinebookmark',
            index=models.Index(fields=['guideline', 'is_active'], name='api_guideli_guideli_1f3a4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guidelinebookmark',
            unique_together={('user', 'guideline')},
        ),
    ]