# Generated by Django 5.0.1 on 2025-06-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_simplify_clinical_guidelines_file_handling'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clinicalguideline',
            new_name='api_clinica_organiz_de13cc_idx',
            old_name='api_clinica_organiz_a4a6c3_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicalguideline',
            new_name='api_clinica_categor_484863_idx',
            old_name='api_clinica_categor_1e5a8f_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicalguideline',
            new_name='api_clinica_approva_31457b_idx',
            old_name='api_clinica_approva_8d2b4c_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicalguideline',
            new_name='api_clinica_effecti_e92425_idx',
            old_name='api_clinica_effecti_7c3e9a_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicalguideline',
            new_name='api_clinica_created_1ddbb7_idx',
            old_name='api_clinica_created_2f1d8b_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicalguideline',
            new_name='api_clinica_guideli_0289be_idx',
            old_name='api_clinica_guideli_5a4b7c_idx',
        ),
        migrations.RenameIndex(
            model_name='guidelineaccess',
            new_name='api_guideli_guideli_109dff_idx',
            old_name='api_guideli_guideli_9e6f8a_idx',
        ),
        migrations.RenameIndex(
            model_name='guidelineaccess',
            new_name='api_guideli_user_id_b85af3_idx',
            old_name='api_guideli_user_id_3b2c5d_idx',
        ),
        migrations.RenameIndex(
            model_name='guidelineaccess',
            new_name='api_guideli_action_756326_idx',
            old_name='api_guideli_action_7a8c9e_idx',
        ),
        migrations.RenameIndex(
            model_name='guidelineaccess',
            new_name='api_guideli_guideli_e2e6eb_idx',
            old_name='api_guideli_guideli_4f5a6b_idx',
        ),
        migrations.RenameIndex(
            model_name='guidelinebookmark',
            new_name='api_guideli_user_id_52fb62_idx',
            old_name='api_guideli_user_id_8c9d2e_idx',
        ),
        migrations.RenameIndex(
            model_name='guidelinebookmark',
            new_name='api_guideli_guideli_87c6a4_idx',
            old_name='api_guideli_guideli_1f3a4b_idx',
        ),
        migrations.RemoveField(
            model_name='clinicalguideline',
            name='file_document',
        ),
        migrations.AddField(
            model_name='clinicalguideline',
            name='file_path',
            field=models.CharField(blank=True, help_text='Path to uploaded guideline file', max_length=500, null=True),
        ),
    ]
