# Generated by Django 5.0.1 on 2025-10-21 18:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_create_messaging_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phb_pharmacy_code', models.CharField(db_index=True, help_text='PHB pharmacy code (e.g., PHB-PH-001)', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(db_index=True, max_length=10)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('electronic_prescriptions_enabled', models.BooleanField(default=False, help_text='Can receive electronic prescriptions via PHB system')),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text="Format: {'monday': {'open': '09:00', 'close': '18:00', 'closed': False}, ...}")),
                ('services_offered', models.JSONField(blank=True, default=list, help_text="List of services: ['prescription_collection', 'flu_jab', 'health_check', 'delivery', ...]")),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='Latitude coordinate for map display', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='Longitude coordinate for map display', max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether pharmacy is currently active in the system')),
                ('verified', models.BooleanField(default=False, help_text='Whether pharmacy has been verified by PHB admin')),
                ('description', models.TextField(blank=True, help_text='Brief description of the pharmacy')),
                ('hospital', models.ForeignKey(blank=True, help_text='If pharmacy is part of a hospital', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_pharmacies', to='api.hospital')),
            ],
            options={
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NominatedPharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomination_type', models.CharField(choices=[('repeat', 'Repeat nomination'), ('acute', 'Acute nomination')], default='repeat', help_text='Type of nomination - repeat for all prescriptions', max_length=20)),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Only one current nomination per user allowed')),
                ('nominated_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this nomination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_nominations', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='api.pharmacy')),
            ],
            options={
                'ordering': ['-nominated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['phb_pharmacy_code'], name='api_pharmac_phb_pha_9ede6d_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['postcode'], name='api_pharmac_postcod_78fd19_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['latitude', 'longitude'], name='api_pharmac_latitud_7251c1_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['electronic_prescriptions_enabled', 'is_active'], name='api_pharmac_electro_8ed5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='nominatedpharmacy',
            index=models.Index(fields=['user', 'is_current'], name='api_nominat_user_id_d81f16_idx'),
        ),
        migrations.AddIndex(
            model_name='nominatedpharmacy',
            index=models.Index(fields=['pharmacy', 'is_current'], name='api_nominat_pharmac_6ac29f_idx'),
        ),
        migrations.AddConstraint(
            model_name='nominatedpharmacy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user', 'is_current'), name='unique_current_nomination_per_user'),
        ),
    ]
