# Generated by Django 5.0.1 on 2025-10-21 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_create_pharmacy_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='nominated_pharmacy',
            field=models.ForeignKey(blank=True, help_text="Patient's nominated pharmacy for this prescription (auto-assigned from user's current nomination)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominated_prescriptions', to='api.pharmacy'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='pharmacy_name',
            field=models.CharField(blank=True, help_text='Dispensing pharmacy name (legacy field - use nominated_pharmacy for structured data)', max_length=255, null=True),
        ),
    ]
