# Generated by Django 5.0.1 on 2025-10-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_add_nominated_pharmacy_to_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dispensed',
            field=models.BooleanField(default=False, help_text='Whether prescription has been dispensed/collected'),
        ),
        migrations.AddField(
            model_name='medication',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time prescription was dispensed', null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='dispensed_by_pharmacy',
            field=models.ForeignKey(blank=True, help_text='Pharmacy that dispensed the prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to='api.pharmacy'),
        ),
        migrations.AddField(
            model_name='medication',
            name='dispensing_pharmacist_name',
            field=models.CharField(blank=True, help_text='Name of pharmacist who dispensed the medication', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='nonce',
            field=models.UUIDField(blank=True, help_text='One-time verification token for prescription security', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='signature',
            field=models.CharField(blank=True, help_text='HMAC-SHA256 signature for prescription verification', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='verification_attempts',
            field=models.JSONField(default=list, help_text='Log of all verification attempts for audit trail'),
        ),
    ]
