# Generated by Django 5.0.1 on 2025-11-01 21:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_add_prescription_security_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the prescription request', primary_key=True, serialize=False)),
                ('request_reference', models.CharField(db_index=True, help_text='Human-readable reference number (e.g., REQ-ABC123)', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', help_text='Current status of the prescription request', max_length=20)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent')], db_index=True, default='routine', help_text='Urgency level (urgent = 1-3 days, routine = 7-10 days)', max_length=10)),
                ('request_type', models.CharField(choices=[('repeat', 'Repeat Prescription'), ('new', 'New Medication'), ('dosage_change', 'Dosage Change')], default='repeat', help_text='Type of prescription request', max_length=20)),
                ('request_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the request was submitted')),
                ('reviewed_date', models.DateTimeField(blank=True, help_text='When the request was reviewed by a doctor', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Clinical reason for rejection (if rejected)', null=True)),
                ('clinical_notes', models.TextField(blank=True, help_text="Doctor's clinical notes about the approval/rejection", null=True)),
                ('requires_followup', models.BooleanField(default=False, help_text='Whether patient needs follow-up appointment (for rejections)')),
                ('additional_notes', models.TextField(blank=True, help_text="Patient's additional notes about the request", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
                ('hospital', models.ForeignKey(help_text='Hospital where request is sent', on_delete=django.db.models.deletion.CASCADE, related_name='prescription_requests', to='api.hospital')),
                ('patient', models.ForeignKey(help_text='Patient who submitted the request', on_delete=django.db.models.deletion.CASCADE, related_name='prescription_requests', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(blank=True, help_text='Nominated pharmacy for collection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_requests', to='api.pharmacy')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Doctor who reviewed/approved/rejected the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prescription_requests', to='api.doctor')),
            ],
            options={
                'verbose_name': 'Prescription Request',
                'verbose_name_plural': 'Prescription Requests',
                'db_table': 'prescription_requests',
                'ordering': ['-urgency', '-request_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(help_text='Name of the medication', max_length=255)),
                ('strength', models.CharField(blank=True, help_text='Strength/dosage (e.g., 500mg, 10ml)', max_length=50, null=True)),
                ('form', models.CharField(blank=True, help_text='Form (tablet, capsule, liquid, inhaler, etc.)', max_length=50, null=True)),
                ('quantity', models.IntegerField(default=0, help_text='Requested quantity')),
                ('dosage', models.TextField(blank=True, help_text='Requested dosage instructions', null=True)),
                ('is_repeat', models.BooleanField(default=False, help_text='Whether this is a repeat prescription')),
                ('reason', models.TextField(blank=True, help_text='Reason for request (required for new medications)', null=True)),
                ('approved_quantity', models.IntegerField(blank=True, help_text='Doctor-approved quantity (may differ from requested)', null=True)),
                ('approved_dosage', models.TextField(blank=True, help_text='Doctor-approved dosage instructions', null=True)),
                ('refills_allowed', models.IntegerField(default=0, help_text='Number of refills allowed (0-11)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the item was created')),
                ('request', models.ForeignKey(help_text='Parent prescription request', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='api.prescriptionrequest')),
            ],
            options={
                'verbose_name': 'Prescription Request Item',
                'verbose_name_plural': 'Prescription Request Items',
                'db_table': 'prescription_request_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='prescriptionrequest',
            index=models.Index(fields=['-request_date'], name='idx_pr_req_date'),
        ),
        migrations.AddIndex(
            model_name='prescriptionrequest',
            index=models.Index(fields=['status', '-request_date'], name='idx_pr_status_date'),
        ),
        migrations.AddIndex(
            model_name='prescriptionrequest',
            index=models.Index(fields=['urgency', '-request_date'], name='idx_pr_urgency_date'),
        ),
        migrations.AddIndex(
            model_name='prescriptionrequest',
            index=models.Index(fields=['hospital', '-request_date'], name='idx_pr_hospital_date'),
        ),
        migrations.AddIndex(
            model_name='prescriptionrequest',
            index=models.Index(fields=['patient', '-request_date'], name='idx_pr_patient_date'),
        ),
    ]
