# Generated by Django 5.0.1 on 2025-11-01 23:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_prescriptionrequest_prescriptionrequestitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for pharmacist', primary_key=True, serialize=False)),
                ('pharmacy_license_number', models.CharField(help_text='Pharmacy license registration number', max_length=50, unique=True)),
                ('license_expiry_date', models.DateField(help_text='Pharmacy license expiry date')),
                ('years_of_experience', models.PositiveIntegerField(help_text='Years of professional pharmacy experience')),
                ('qualifications', models.JSONField(blank=True, default=list, help_text='List of pharmacy qualifications (PharmD, MSc, etc.)')),
                ('board_certifications', models.TextField(blank=True, help_text='Pharmacy board certifications (e.g., BCPS, BCACP)', null=True)),
                ('can_review_prescriptions', models.BooleanField(default=True, help_text='Whether pharmacist can review and approve prescription requests')),
                ('prescribing_authority_level', models.CharField(choices=[('none', 'No Prescribing Authority'), ('supplementary', 'Supplementary Prescriber'), ('independent', 'Independent Prescriber'), ('community', 'Community Pharmacist Prescriber')], default='supplementary', help_text='Level of prescribing authority', max_length=20)),
                ('can_prescribe_controlled', models.BooleanField(default=False, help_text='Whether pharmacist can prescribe controlled substances')),
                ('controlled_substance_level', models.CharField(choices=[('none', 'Cannot Prescribe Controlled Substances'), ('schedule_3_5', 'Schedules 3-5 Only'), ('all_schedules', 'All Schedules')], default='none', help_text='Level of controlled substance prescribing authority', max_length=20)),
                ('collaborative_practice_agreement', models.BooleanField(default=False, help_text='Whether pharmacist has CPA with supervising physician')),
                ('triage_specialty', models.CharField(choices=[('general', 'General Pharmacy'), ('cardiology', 'Cardiovascular Medications'), ('diabetes', 'Diabetes & Endocrine'), ('mental_health', 'Mental Health Medications'), ('pediatrics', 'Pediatric Pharmacy'), ('geriatrics', 'Geriatric Pharmacy'), ('oncology', 'Oncology Pharmacy'), ('infectious_disease', 'Infectious Disease'), ('pain_management', 'Pain & Palliative Care'), ('respiratory', 'Respiratory Medications')], default='general', help_text="Pharmacist's specialty for triage assignment", max_length=30)),
                ('auto_assign_triage', models.BooleanField(default=True, help_text='Whether to auto-assign prescription requests to this pharmacist')),
                ('max_daily_reviews', models.PositiveIntegerField(default=30, help_text='Maximum prescription reviews per day')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the pharmacist is currently practicing')),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('retired', 'Retired')], default='active', help_text='Current working status', max_length=20)),
                ('available_for_reviews', models.BooleanField(default=True, help_text='Whether accepting new prescription reviews')),
                ('working_hours_start', models.TimeField(blank=True, help_text='Start time of working hours', null=True)),
                ('working_hours_end', models.TimeField(blank=True, help_text='End time of working hours', null=True)),
                ('working_days', models.CharField(default='Mon,Tue,Wed,Thu,Fri', help_text="Comma-separated days, e.g., 'Mon,Tue,Wed'", max_length=100)),
                ('total_reviews_completed', models.PositiveIntegerField(default=0, help_text='Total prescription reviews completed')),
                ('total_approved', models.PositiveIntegerField(default=0, help_text='Total prescriptions approved by pharmacist')),
                ('total_escalated', models.PositiveIntegerField(default=0, help_text='Total prescriptions escalated to physician')),
                ('total_rejected', models.PositiveIntegerField(default=0, help_text='Total prescription requests rejected')),
                ('average_review_time_minutes', models.FloatField(default=0.0, help_text='Average time to review prescription request (minutes)')),
                ('clinical_interventions_count', models.PositiveIntegerField(default=0, help_text='Number of clinical interventions made (drug interactions, dosage corrections, etc.)')),
                ('clinical_interests', models.TextField(blank=True, help_text='Areas of clinical pharmacy interest', null=True)),
                ('languages_spoken', models.CharField(blank=True, help_text='Comma-separated languages', max_length=200, null=True)),
                ('pharmacy_school', models.CharField(blank=True, help_text='Pharmacy school attended', max_length=200, null=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, help_text='Year of pharmacy school graduation', null=True)),
                ('professional_email', models.EmailField(blank=True, help_text='Professional email for prescription notifications', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Professional phone number', max_length=20, null=True)),
                ('notification_preferences', models.JSONField(blank=True, default=dict, help_text='Notification preferences for prescription reviews')),
                ('hospital', models.ForeignKey(blank=True, help_text='Primary hospital affiliation (if hospital pharmacist)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacists', to='api.hospital')),
                ('supervising_physician', models.ForeignKey(blank=True, help_text="Physician overseeing pharmacist's prescribing activities (for CPA)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_pharmacists', to='api.doctor')),
                ('user', models.OneToOneField(help_text='User account associated with this pharmacist', on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacist',
                'verbose_name_plural': 'Pharmacists',
                'db_table': 'pharmacists',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'is_active'], name='idx_pharmacist_hospital_active'), models.Index(fields=['triage_specialty', 'auto_assign_triage'], name='idx_pharmacist_triage'), models.Index(fields=['status', 'available_for_reviews'], name='idx_pharmacist_availability'), models.Index(fields=['prescribing_authority_level'], name='idx_pharmacist_authority')],
            },
        ),
    ]
