# Generated by Django 5.0.1 on 2025-11-01 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_pharmacist'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionrequest',
            name='assigned_to_doctor',
            field=models.ForeignKey(blank=True, help_text='Specific doctor assigned to review (if assigned_to_role is doctor)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prescription_requests', to='api.doctor'),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='assigned_to_pharmacist',
            field=models.ForeignKey(blank=True, help_text='Specific pharmacist assigned to review (if assigned_to_role is pharmacist)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prescription_requests', to='api.pharmacist'),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='assigned_to_role',
            field=models.CharField(choices=[('pharmacist', 'Pharmacist'), ('doctor', 'Doctor'), ('admin', 'Admin Staff')], db_index=True, default='pharmacist', help_text='Role assigned to review this request', max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='clinical_concerns',
            field=models.TextField(blank=True, help_text='Specific clinical concerns identified by pharmacist', null=True),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='drug_interactions_checked',
            field=models.TextField(blank=True, help_text='Results of drug interaction check', null=True),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='escalation_reason',
            field=models.TextField(blank=True, help_text='Reason for escalating to physician (if escalated)', null=True),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='had_clinical_intervention',
            field=models.BooleanField(default=False, help_text='Whether pharmacist made a clinical intervention (dosage adjustment, drug interaction warning, etc.)'),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='monitoring_requirements',
            field=models.TextField(blank=True, help_text='Required monitoring (e.g., lab tests, blood pressure checks)', null=True),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='pharmacist_notes',
            field=models.TextField(blank=True, help_text="Pharmacist's clinical notes and recommendations", null=True),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='pharmacist_recommendation',
            field=models.TextField(blank=True, help_text="Pharmacist's recommendation to the physician", null=True),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='pharmacist_review_action',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('escalated', 'Escalated to Physician'), ('rejected', 'Rejected'), ('consultation', 'Patient Consultation Required')], help_text='Action taken by pharmacist', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='pharmacist_review_date',
            field=models.DateTimeField(blank=True, help_text='When the pharmacist reviewed the request', null=True),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='pharmacist_review_time_minutes',
            field=models.FloatField(blank=True, help_text='Time taken by pharmacist to review (in minutes)', null=True),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='pharmacist_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Pharmacist who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prescription_requests', to='api.pharmacist'),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='triage_category',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-assigned triage category (e.g., ROUTINE_REPEAT, URGENT_NEW, COMPLEX_CASE)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='triage_reason',
            field=models.TextField(blank=True, help_text='Explanation of why this triage category was assigned', null=True),
        ),
        migrations.AddIndex(
            model_name='prescriptionrequest',
            index=models.Index(fields=['assigned_to_role', 'status', '-request_date'], name='idx_pr_role_status'),
        ),
        migrations.AddIndex(
            model_name='prescriptionrequest',
            index=models.Index(fields=['triage_category', '-request_date'], name='idx_pr_triage_cat'),
        ),
        migrations.AddIndex(
            model_name='prescriptionrequest',
            index=models.Index(fields=['assigned_to_pharmacist', 'status'], name='idx_pr_pharm_status'),
        ),
        migrations.AddIndex(
            model_name='prescriptionrequest',
            index=models.Index(fields=['assigned_to_doctor', 'status'], name='idx_pr_doc_status'),
        ),
        migrations.AddIndex(
            model_name='prescriptionrequest',
            index=models.Index(fields=['pharmacist_review_action', '-pharmacist_review_date'], name='idx_pr_pharm_review'),
        ),
    ]
