# Generated by Django 5.0.1 on 2025-11-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_role_customuser_registry_role_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='locked_after_verification',
            field=models.BooleanField(default=False, help_text='Whether this document is locked and cannot be modified after verification (prevents changes during re-upload of other docs)'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='max_rejection_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of times this document can be rejected before requiring admin intervention'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='rejection_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this document has been rejected'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='resubmission_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for re-uploading a rejected document (typically 7 days from rejection)', null=True),
        ),
        migrations.AddField(
            model_name='professionalapplication',
            name='has_rejected_documents',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag indicating application has one or more rejected documents that need resubmission'),
        ),
    ]
