# Generated by Django 5.0.1 on 2025-11-07 14:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_add_document_rejection_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualServiceOffering',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(help_text="Name of virtual service (e.g., 'Online Consultation')", max_length=200)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Typical consultation duration')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Naira', max_digits=10)),
                ('availability_schedule', models.JSONField(blank=True, default=dict, help_text='Weekly availability slots')),
                ('booking_url', models.URLField(blank=True, help_text='Direct booking link for this service')),
                ('is_active', models.BooleanField(default=True, help_text='Whether service is currently offered')),
            ],
            options={
                'verbose_name': 'Virtual Service Offering',
                'verbose_name_plural': 'Virtual Service Offerings',
                'db_table': 'virtual_service_offerings',
                'ordering': ['service_name'],
            },
        ),
        migrations.AlterField(
            model_name='nominatedpharmacy',
            name='pharmacy',
            field=models.ForeignKey(blank=True, help_text='Admin-created pharmacy (can be hospital-affiliated)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='api.pharmacy'),
        ),
        migrations.CreateModel(
            name='ProfessionalPracticePage',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('practice_name', models.CharField(help_text="Name of practice (e.g., 'Golden Pharmacy Abuja')", max_length=200)),
                ('slug', models.SlugField(help_text="URL-friendly slug (e.g., 'golden-pharmacy-abuja')", max_length=250, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Short description for SEO and previews', max_length=160)),
                ('about', models.TextField(blank=True, help_text='Detailed about section (rich text supported)')),
                ('service_type', models.CharField(choices=[('in_store', 'In-Store/Walk-In Service'), ('virtual', 'Virtual Service Only'), ('both', 'Both In-Store and Virtual')], help_text='Type of service offered', max_length=20)),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='Operating hours for in-store services')),
                ('virtual_consultation_hours', models.JSONField(blank=True, default=dict, help_text='Availability for virtual consultations')),
                ('online_booking_url', models.URLField(blank=True, help_text='Link to booking system for virtual appointments')),
                ('video_platform', models.CharField(blank=True, help_text='Platform used (Zoom, Google Meet, etc.)', max_length=100)),
                ('services_offered', models.JSONField(blank=True, default=list, help_text='List of services with optional pricing')),
                ('payment_methods', models.JSONField(blank=True, default=list, help_text='Accepted payment methods')),
                ('additional_certifications', models.JSONField(blank=True, default=list, help_text='Certifications beyond PHB license')),
                ('languages_spoken', models.JSONField(blank=True, default=list, help_text='Languages spoken at practice')),
                ('is_published', models.BooleanField(default=False, help_text='Whether page is publicly visible')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('flagged', 'Flagged for Review'), ('suspended', 'Suspended')], default='pending', help_text='Admin verification status', max_length=20)),
                ('verification_notes', models.TextField(blank=True, help_text='Admin notes about verification')),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times page viewed')),
                ('nomination_count', models.PositiveIntegerField(default=0, help_text='Number of times nominated by patients')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords', max_length=255)),
                ('linked_registry_entry', models.ForeignKey(help_text='Link to verified PHB registry entry', on_delete=django.db.models.deletion.PROTECT, related_name='practice_pages', to='api.phbprofessionalregistry')),
                ('owner', models.OneToOneField(help_text='Professional who owns this page', on_delete=django.db.models.deletion.CASCADE, related_name='practice_page', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_practice_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professional Practice Page',
                'verbose_name_plural': 'Professional Practice Pages',
                'db_table': 'professional_practice_pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalLocation',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Location name (e.g., 'Main Branch', 'Ikeja Office')", max_length=200)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the main location?')),
                ('practice_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.professionalpracticepage')),
            ],
            options={
                'verbose_name': 'Physical Location',
                'verbose_name_plural': 'Physical Locations',
                'db_table': 'physical_locations',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AddField(
            model_name='nominatedpharmacy',
            name='practice_page',
            field=models.ForeignKey(blank=True, help_text='Professional-created practice page (mutually exclusive with pharmacy)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='api.professionalpracticepage'),
        ),
        migrations.AddConstraint(
            model_name='nominatedpharmacy',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('pharmacy__isnull', False), ('practice_page__isnull', True)), models.Q(('pharmacy__isnull', True), ('practice_page__isnull', False)), _connector='OR'), name='pharmacy_or_practice_page_not_both'),
        ),
        migrations.AddField(
            model_name='virtualserviceoffering',
            name='practice_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_services', to='api.professionalpracticepage'),
        ),
        migrations.AddIndex(
            model_name='professionalpracticepage',
            index=models.Index(fields=['slug'], name='professiona_slug_f0e2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalpracticepage',
            index=models.Index(fields=['is_published', 'verification_status'], name='professiona_is_publ_3397cb_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalpracticepage',
            index=models.Index(fields=['service_type'], name='professiona_service_6feae4_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalpracticepage',
            index=models.Index(fields=['city', 'state'], name='professiona_city_30918a_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalpracticepage',
            index=models.Index(fields=['latitude', 'longitude'], name='professiona_latitud_ddf67d_idx'),
        ),
    ]
