# Generated by Django 5.0.1 on 2025-11-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_virtualserviceoffering_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitallicense',
            options={'ordering': ['-created_at', 'license_type'], 'permissions': [('can_manage_licenses', 'Can manage hospital licenses'), ('can_view_license_details', 'Can view license details'), ('can_verify_licenses', 'Can verify license status'), ('can_upload_documents', 'Can upload license documents')]},
        ),
        migrations.AlterUniqueTogether(
            name='hospitallicense',
            unique_together={('hospital', 'license_number')},
        ),
        migrations.AlterField(
            model_name='hospitallicense',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Date license becomes effective', null=True),
        ),
        migrations.AlterField(
            model_name='hospitallicense',
            name='issue_date',
            field=models.DateField(blank=True, help_text='Date license was issued', null=True),
        ),
    ]
