# Generated by Django 5.0.1 on 2025-11-08 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_hospitallicense_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitallicense',
            name='healthcare_authority',
            field=models.ForeignKey(blank=True, help_text='Healthcare authority that issued this license (not applicable for CAC certificates)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_licenses', to='api.healthcareauthority'),
        ),
    ]
