# Generated by Django 5.0.1 on 2025-11-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_hospitallicense_healthcare_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitallicense',
            name='license_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('pending', 'Pending Approval'), ('renewal_pending', 'Renewal Pending'), ('under_review', 'Under Review')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitallicense',
            name='license_type',
            field=models.CharField(choices=[('business_registration', 'Business Registration (CAC)'), ('operating', 'Operating License'), ('emergency', 'Emergency Services License'), ('surgical', 'Surgical Services License'), ('maternity', 'Maternity Services License'), ('icu', 'ICU/Critical Care License'), ('psychiatric', 'Psychiatric Services License'), ('pediatric', 'Pediatric Services License'), ('radiology', 'Radiology/Imaging License'), ('laboratory', 'Laboratory Services License'), ('pharmacy', 'Hospital Pharmacy License'), ('blood_bank', 'Blood Bank License'), ('ambulance', 'Ambulance Services License'), ('research', 'Medical Research License'), ('teaching', 'Teaching Hospital License'), ('specialty', 'Specialty Services License'), ('other', 'Other License Type')], default='operating', max_length=30),
        ),
    ]
