# Generated by Django 5.0.1 on 2025-11-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_change_license_default_status_to_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PHB Administration', help_text='Name to display under signature', max_length=100)),
                ('signature_image', models.ImageField(help_text='Upload your signature (PNG with transparent background recommended)', upload_to='signatures/')),
                ('is_active', models.BooleanField(default=True, help_text='Use this signature for certificates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Signature',
                'verbose_name_plural': 'Admin Signatures',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
