# Generated by Django 5.0.1 on 2025-11-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_adminsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='administrative_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='administrative_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='administrative_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='administrative_contact_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='certification_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Certification fees in NGN', max_digits=10),
        ),
        migrations.AddField(
            model_name='hospital',
            name='government_license_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Government license fees in NGN', max_digits=10),
        ),
        migrations.AddField(
            model_name='hospital',
            name='medical_director_license',
            field=models.CharField(blank=True, help_text='Medical Director License Number (e.g., MDCN-45678)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='medical_director_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='medical_director_specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='medical_director_years_experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='minimum_doctors_required',
            field=models.PositiveIntegerField(default=10, help_text='Minimum number of doctors required'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='minimum_nurses_required',
            field=models.PositiveIntegerField(default=25, help_text='Minimum number of nurses required'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='primary_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='primary_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='primary_contact_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_registration_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total paid registration fees in NGN', max_digits=10),
        ),
    ]
