# Generated by Django 5.0.1 on 2025-11-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_hospital_administrative_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='has_api_integration',
            field=models.BooleanField(default=False, help_text='Ready to integrate with external healthcare systems'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='has_electronic_medical_records',
            field=models.BooleanField(default=False, help_text='Electronic Medical Records (EMR)'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='has_hospital_information_system',
            field=models.BooleanField(default=False, help_text='Hospital Information System (HIS)'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='has_mobile_application',
            field=models.BooleanField(default=False, help_text='Mobile application'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='has_online_appointment_booking',
            field=models.BooleanField(default=False, help_text='Online appointment booking system'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='has_patient_portal',
            field=models.BooleanField(default=False, help_text='Patient portal access'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='has_telemedicine_capabilities',
            field=models.BooleanField(default=False, help_text='Telemedicine capabilities'),
        ),
    ]
