# Generated by Django 5.0.1 on 2025-11-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_hospital_has_api_integration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when consultation was started', null=True),
        ),
    ]
