# Generated by Django 5.0.1 on 2025-11-12 20:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_appointment_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_hpn', models.CharField(db_index=True, help_text="Patient's HPN that was searched", max_length=30)),
                ('access_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the access occurred')),
                ('access_type', models.CharField(choices=[('search', 'HPN Search'), ('view', 'View Prescriptions'), ('dispense', 'Dispense Medication')], default='search', help_text='Type of access performed', max_length=20)),
                ('prescriptions_accessed', models.JSONField(default=list, help_text='List of prescription IDs accessed in this session')),
                ('prescription_count', models.IntegerField(default=0, help_text='Number of prescriptions viewed')),
                ('controlled_substance_count', models.IntegerField(default=0, help_text='Number of controlled substance prescriptions accessed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the access', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent')),
                ('patient_verified', models.BooleanField(default=False, help_text='Whether patient identity was verified')),
                ('verification_method', models.CharField(blank=True, choices=[('', 'Not Verified'), ('hpn_name', 'HPN + Name Match'), ('government_id', 'Government ID'), ('biometric', 'Biometric')], help_text='Method used to verify patient identity', max_length=50)),
                ('access_granted', models.BooleanField(default=True, help_text='Whether access was successfully granted')),
                ('denial_reason', models.CharField(blank=True, help_text='Reason if access was denied', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this access')),
                ('patient_user', models.ForeignKey(help_text='Patient user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_lookups', to=settings.AUTH_USER_MODEL)),
                ('pharmacist_user', models.ForeignKey(help_text='Pharmacist user who accessed the prescription', on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_access_logs', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(help_text='Pharmacy that accessed the prescription', on_delete=django.db.models.deletion.CASCADE, related_name='prescription_access_logs', to='api.pharmacy')),
            ],
            options={
                'verbose_name': 'Pharmacy Access Log',
                'verbose_name_plural': 'Pharmacy Access Logs',
                'ordering': ['-access_time'],
                'indexes': [models.Index(fields=['pharmacy', 'access_time'], name='api_pharmac_pharmac_e5bf28_idx'), models.Index(fields=['patient_hpn', 'access_time'], name='api_pharmac_patient_506813_idx'), models.Index(fields=['pharmacist_user', 'access_time'], name='api_pharmac_pharmac_df5925_idx'), models.Index(fields=['access_type', 'access_time'], name='api_pharmac_access__23c990_idx')],
            },
        ),
    ]
