# Generated by Django 5.0.1 on 2025-11-12 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_pharmacyaccesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyaccesslog',
            name='pharmacy',
            field=models.ForeignKey(blank=True, help_text='Pharmacy that accessed the prescription', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_access_logs', to='api.pharmacy'),
        ),
    ]
