# Generated by Django 5.0.1 on 2025-11-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_pharmacyaccesslog_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='is_controlled_override',
            field=models.BooleanField(default=False, help_text='Doctor manually marked as controlled substance (even if not in drug database)'),
        ),
    ]
